import fields from './bambu-project-fields.json' with {type:'json'};
import {requireThat} from '../geom/tolerance.mjs';

// Project preferences and resolved slice CONFIG have different schemas.
// Keep the authored assignments consistent; a reference's saved automatic
// preferences are not evidence for changing this job's resolved routing.
export function resolveBambuProject(plan,machine,output,settings,selections){
  if(output.package.projectSchema===undefined&&machine.id!=='bambu-h2d')return settings;
  requireThat(machine.id==='bambu-h2d'&&output.package.projectSchema==='h2d-full-project-v1','Unknown Bambu project schema.');
  const s=plan.setup,k=output.constraints,filaments=settings.filament_ids.length;
  const repeat=(value,count)=>Array.from({length:count},()=>String(value));
  const p={...fields.scalar,...structuredClone(fields.lists)};
  for(const [scope,count]of [['filament',filaments],['tool',machine.tools.length],['toolMode',machine.tools.length*2],['filamentDryer',filaments*4]]){
    for(const [key,value]of Object.entries(fields[scope]))p[key]=repeat(value,count);
  }
  for(const [key,values]of Object.entries(fields.filamentAMS))p[key]=Array.from({length:filaments},()=>values).flat();
  // Canonical job values always win. Nothing in a compatibility default may
  // override an installed nozzle, logical filament, temperature or plate.
  Object.assign(p,structuredClone(settings));delete p.filament_map_2;
  const perFilament=fn=>selections.map((selection,i)=>String(fn(selection,i)));
  const perTool=fn=>machine.tools.map(t=>String(fn(t)));
  const selectedForTool=t=>selections.find(selection=>selection.setup.tool===t.index)??selections[plan.setup.bambu.filament];
  const rectangle=b=>[`${b.min[0]}x${b.min[1]}`,`${b.max[0]}x${b.min[1]}`,`${b.max[0]}x${b.max[1]}`,`${b.min[0]}x${b.max[1]}`];
  Object.assign(p,{
    name:'project_settings',from:'project',version:output.package.clientVersion,
    printer_model:machine.name,printer_variant:String(s.nozzleMm),printer_settings_id:settings.printer_settings_id,
    print_settings_id:'SAAM authored path',default_print_profile:'SAAM authored path',filename_format:'SAAM.gcode',
    printer_notes:'SAAM Standard-nozzle PLA output',process_notes:'Geometry and motion are generated by SAAM; project fields describe the job and compatibility defaults.',
    printable_area:rectangle(machine.bounds),printable_height:String(machine.bounds.max[2]),
    extruder_printable_area:perTool(t=>rectangle(t.bounds).join(',')),extruder_printable_height:perTool(t=>t.bounds.max[2]),
    extruder_variant_list:perTool(()=>'Direct Drive Standard'),
    nozzle_volume:perTool(t=>t.physicalExtruder===0?145:130),
    default_nozzle_volume_type:[...settings.nozzle_volume_type],
    min_layer_height:perTool(t=>t.layerHeightMm[0]),max_layer_height:perTool(t=>t.layerHeightMm[1]),
    filament_settings_id:perFilament((selection,i)=>`SAAM ${selection.setup.material} ${settings.filament_ids[i]}`),
    filament_multi_colour:[...settings.filament_colour],default_filament_colour:[...settings.filament_colour],
    default_filament_profile:['SAAM PLA'],print_compatible_printers:[settings.printer_settings_id],upward_compatible_machine:[],
    filament_vendor:repeat('',filaments),filament_notes:repeat('',filaments),
    filament_max_volumetric_speed:perFilament(selection=>selection.process.maxFlowMm3S),
    filament_retraction_length:perFilament(selection=>selection.process.retractMm),
    filament_cooling_before_tower:repeat(0,filaments),
    filament_flush_temp:repeat(k.startupFlushC,filaments),filament_flush_temp_fast:repeat(k.startupFlushC,filaments),
    filament_flush_volumetric_speed:repeat(k.startupPurgeFlowMm3S,filaments),
    hotend_cooling_rate:perTool(()=>k.hotendCoolingRateCPerS),hotend_heating_rate:perTool(()=>k.hotendHeatingRateCPerS),
    flush_volumes_matrix:machine.tools.flatMap(()=>Array.from({length:filaments},(_,from)=>Array.from({length:filaments},(_,to)=>String(from===to?0:k.materialChangeFlushMm3))).flat()),
    flush_volumes_vector:repeat(k.materialChangeFlushMm3,filaments*machine.tools.length),
    default_acceleration:perTool(()=>k.bodyAcceleration),travel_acceleration:perTool(()=>k.bodyAcceleration),
    travel_speed:perTool(t=>selectedForTool(t).process.travelSpeedMmS),
    retraction_length:perTool(t=>selectedForTool(t).process.retractMm),
    retract_length_toolchange:perTool(t=>selectedForTool(t).process.retractMm),
    line_width:String(plan.process.lineWidthMm),initial_layer_line_width:String(plan.process.lineWidthMm),
    enable_prime_tower:'0',enable_tower_interface_features:'0',use_relative_e_distances:'1',
  });
  for(const axis of ['x','y','z','e'])p['machine_max_speed_'+axis]=repeat(machine.maxFeedMmS[axis],machine.tools.length*2);
  for(const key of Object.keys(p))if(/^(?:cool|eng|hot|textured|supertack)_plate_temp(?:_initial_layer)?$/.test(key))p[key]=repeat(s.bedC,filaments);
  // Validate field types. The explicit scopes above choose cardinalities;
  // array length never determines a role (two colours can equal two tools).
  for(const [key,values]of Object.entries(p))requireThat(typeof values==='string'||Array.isArray(values)&&values.every(v=>typeof v==='string'),`Invalid project field ${key}.`);
  return Object.fromEntries(Object.entries(p).sort(([a],[b])=>a.localeCompare(b,'en')));
}

export function serializeBambuProject(project){
  return JSON.stringify(project,null,4).replaceAll('\n','\r\n')+'\r\n';
}
