// Bounded H2D output, not an interpreter for arbitrary Bambu Studio jobs.
// Firmware service commands are matched to a pinned envelope. The intervening
// print body is reconstructed by the shared modal G-code interpreter.
import {createHash} from 'node:crypto';
import {deflateSync} from 'node:zlib';
import {exportMotion,interpretMotion,validatePath} from './griffin.mjs';
import {packZip,unpackZip,crc32} from './zip.mjs';
import {requireThat} from '../geom/tolerance.mjs';
import {validateSetup,checkMachinePath,toolFor,toolBounds} from '../machine/profile.mjs';
const digest=(bytes,algorithm='sha256')=>createHash(algorithm).update(bytes).digest('hex');
const fmt=(n,d=5)=>Number(n.toFixed(d));
const json=value=>JSON.stringify(value)+'\n';
const xml=value=>String(value).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const meta=values=>Object.entries(values).map(([k,v])=>`    <metadata key="${k}" value="${xml(v)}"/>`).join('\n');
const BEGIN=';SAAM_BODY_BEGIN\n',END=';SAAM_BODY_END\n',GCODE='Metadata/plate_1.gcode';
const CONTRACT='h2d-02.08.02.61-pla-textured-v1';
// Updated only after reviewing changes to the firmware service contract.
const ENVELOPE_HASH='8fdee627792030a4f8b614752257b7b2756df1ba2693d5087997084ac4970807';
function configuration(plan,machine){
  validateSetup(plan,machine);
  const output=machine.outputs.find(o=>o.id===plan.output),t=toolFor(machine,plan.setup.tool),s=plan.setup;
  requireThat(machine.id==='bambu-h2d'&&plan.output==='bambu-gcode'&&output?.program?.contract===CONTRACT,'Unsupported H2D output contract.');
  requireThat(digest(JSON.stringify([output.program.start,output.program.end]))===ENVELOPE_HASH,'Unknown H2D firmware envelope; an interpreter update is required.');
  requireThat(s.material==='PLA'&&s.nozzleMm===0.4&&s.filamentMm===1.75&&s.buildVolumeC===0,'H2D output requires 0.4 mm PLA, 1.75 mm filament and no chamber heating.');
  requireThat(t.physicalExtruder===1-s.tool&&JSON.stringify(t.startupXY)==='[100,100]'&&machine.startup.zAfterStartupMm===20,'H2D tool/startup contract mismatch.');
  return output;
}
function contextFor(path,plan,machine,release){
  const moves=path.actions.filter(a=>a.kind==='move'),points=[path.initialPosition,...moves.map(m=>m.to)];
  const deposits=moves.filter(m=>m.volumeMm3>0);requireThat(deposits.length,'H2D output needs deposition.');
  const bounds=path.summary?.boundsMm;
  const layers=new Set(deposits.map(m=>`${m.phase}:${m.layer}`));
  const context={schema:'saam-h2d-artifact/1',contract:CONTRACT,release,bounds,initialPosition:path.initialPosition,
    pathMaxZ:points.reduce((maximum,p)=>Math.max(maximum,p[2]),-Infinity),layers:layers.size};
  checkContext(context,plan,machine);return context;
}
function checkContext(c,plan,machine){
  const b=toolBounds(machine,plan.setup.tool);
  requireThat(c?.schema==='saam-h2d-artifact/1'&&c.contract===CONTRACT&&JSON.stringify(c.initialPosition)==='[100,100,20]','Invalid H2D artifact context.');
  requireThat(c.bounds&&['min','max'].every(k=>Array.isArray(c.bounds[k])&&c.bounds[k].length===3&&c.bounds[k].every(Number.isFinite)),'Missing H2D geometry bounds.');
  requireThat(c.bounds.min.every((v,i)=>v>=b.min[i]&&v<c.bounds.max[i])&&c.bounds.max.every((v,i)=>v<=b.max[i]),'H2D geometry bounds exceed selected nozzle area.');
  requireThat(Number.isFinite(c.pathMaxZ)&&c.pathMaxZ>=c.bounds.max[2]&&c.pathMaxZ<=b.max[2]&&Math.max(c.pathMaxZ,c.bounds.max[2]+10)<=Math.min(320,b.max[2]),'H2D shutdown clearance exceeds machine bounds.');
  requireThat(Number.isInteger(c.layers)&&c.layers>0&&c.layers<100000,'Invalid H2D layer count.');
  requireThat(c.release&&/^[a-zA-Z0-9.+-]{1,40}$/.test(c.release.generatorVersion)&&/^\d{4}-\d{2}-\d{2}$/.test(c.release.buildDate),'Invalid H2D release metadata.');
}
function sections(c,plan,machine){
  const output=configuration(plan,machine);checkContext(c,plan,machine);
  const endClearanceZ=fmt(Math.max(c.pathMaxZ,c.bounds.max[2]+10));
  const values={...plan.setup,physicalTool:toolFor(machine,plan.setup.tool).physicalExtruder,
    minX:fmt(c.bounds.min[0]),minY:fmt(c.bounds.min[1]),sizeX:fmt(c.bounds.max[0]-c.bounds.min[0]),sizeY:fmt(c.bounds.max[1]-c.bounds.min[1]),
    endClearanceZ,parkZ:fmt(Math.max(endClearanceZ,Math.min(320,100+c.bounds.max[2]/2)))};
  const render=lines=>lines.map(line=>line.replace(/\{([A-Za-z]+)\}/g,(_,key)=>{
    requireThat(Number.isFinite(values[key]),'Unknown H2D template value.');return values[key];
  })).join('\n')+'\n';
  return {start:render(output.program.start),end:render(output.program.end),endClearanceZ};
}
const prelude=plan=>`G90\nG21\nM83\nG92 E0\nM190 S${plan.setup.bedC}\nM109 S${plan.setup.nozzleC}\n`;
function header(c,program){
  return ['; HEADER_BLOCK_START',`; generated by SAAM ${c.release.generatorVersion}`,`; build date: ${c.release.buildDate}`,
    `; total layer number: ${c.layers}`,`; total filament length [mm] : ${fmt(program.summary.filamentMm,2)}`,
    `; total filament volume [cm^3] : ${fmt(program.volumeMm3/1000,4)}`,`; max_z_height: ${fmt(c.bounds.max[2])}`,
    '; filament_diameter: 1.75','; filament: 1','; HEADER_BLOCK_END','; EXECUTABLE_BLOCK_START'].join('\n')+'\n';
}
function interpretBody(body,plan,machine){
  requireThat(body.startsWith(prelude(plan)),'H2D body is missing its explicit modal/temperature state.');
  // Physical T selectors and firmware macros belong only to the pinned envelope.
  requireThat(!body.split('\n').some(l=>/^T\d/.test(l.trim())),'H2D body cannot change the selected tool.');
  const program=interpretMotion(body,plan,machine,{extrusionMode:'relative'}),bounds=toolBounds(machine,plan.setup.tool);
  requireThat(program.moves.every(m=>[m.from,m.to].every(p=>p.every((v,i)=>v>=bounds.min[i]-1e-5&&v<=bounds.max[i]+1e-5))),'H2D body exceeds selected nozzle area.');
  return program;
}

export function exportBambu(path,plan,machine,release){
  configuration(plan,machine);validatePath(path);checkMachinePath(path,plan,machine);
  const c=contextFor(path,plan,machine,release),s=sections(c,plan,machine);
  const body=prelude(plan)+exportMotion(path,plan,{extrusionMode:'relative'}).map(l=>l==='M107'?'M106 S0':l).join('\n')+'\n';
  const program=interpretBody(body,plan,machine);
  const code=header(c,program)+s.start+BEGIN+body+END+s.end+'; EXECUTABLE_BLOCK_END\n';
  return packZip(packageEntries(code,c,program,plan));
}
export function interpretBambu(bytes,plan,machine){
  configuration(plan,machine);const entries=unpackZip(bytes);
  const c=JSON.parse(entries.get('Metadata/saam.json')?.toString()??'null');checkContext(c,plan,machine);
  const code=entries.get(GCODE)?.toString('utf8');requireThat(typeof code==='string'&&code.length<25_000_000,'Missing/oversized H2D G-code.');
  requireThat(code.split(BEGIN).length===2&&code.split(END).length===2,'Invalid H2D body boundary.');
  const body=code.split(BEGIN)[1].split(END)[0],program=interpretBody(body,plan,machine),s=sections(c,plan,machine);
  requireThat(code===header(c,program)+s.start+BEGIN+body+END+s.end+'; EXECUTABLE_BLOCK_END\n','H2D program differs from its declared firmware envelope.');
  requireThat(program.moves.every(m=>m.to[2]<=c.pathMaxZ+1e-5),'H2D body exceeds declared shutdown clearance.');
  const expected=packageEntries(code,c,program,plan);
  requireThat(entries.size===expected.size&&[...expected].every(([name,value])=>entries.get(name)?.equals(Buffer.from(value))),'H2D package metadata, checksum or thumbnail differs from the program.');
  const prefixLines=code.slice(0,code.indexOf(BEGIN)+BEGIN.length).split('\n').length-1;
  for(const event of [...program.moves,...program.events])event.line+=prefixLines;
  program.code=code;
  program.envelope={contract:CONTRACT,simulation:'not simulated',initialPosition:c.initialPosition,endClearanceZ:s.endClearanceZ,
    notice:'Firmware probing, wiping, calibration, purge, unload and service motions are checked against a fixed reference envelope; they are not simulated. Playback and timing cover the print body only.'};
  program.summary.startup=program.envelope.notice;
  program.summary.clearance='Whole-plan travel checked; physical head clearance is not modeled.';
  return program;
}

function packageEntries(code,c,program,plan){
  const tool=plan.setup.tool,map=tool+1,volume=program.volumeMm3,filament=program.summary.filamentMm,weight=volume/1000*1.26;
  const seconds=Math.ceil(program.seconds),bbox=[c.bounds.min[0],c.bounds.min[1],c.bounds.max[0],c.bounds.max[1]];
  const plate={bbox_all:bbox,bbox_objects:[{area:(bbox[2]-bbox[0])*(bbox[3]-bbox[1]),bbox,id:1,layer_height:plan.process.layerMm,name:'SAAM part'}],
    bed_type:'textured_plate',filament_colors:['#28A090'],filament_ids:[0],first_extruder:0,first_layer_time:0,is_seq_print:false,nozzle_diameter:0.4,version:2};
  const entries=new Map([
    [GCODE,code],[GCODE+'.md5',digest(code,'md5')],['Metadata/saam.json',json(c)],
    ['Metadata/plate_1.json',json(plate)],
    ['[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?>\n<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/><Default Extension="png" ContentType="image/png"/><Default Extension="gcode" ContentType="text/x.gcode"/></Types>\n'],
    ['3D/3dmodel.model',`<?xml version="1.0" encoding="UTF-8"?>\n<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:BambuStudio="http://schemas.bambulab.com/package/2021"><metadata name="Application">SAAM-${xml(c.release.generatorVersion)}</metadata><metadata name="BambuStudio:3mfVersion">1</metadata><resources/><build/></model>\n`],
    ['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?>\n<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/><Relationship Target="/Metadata/plate_1.png" Id="rel-2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail"/><Relationship Target="/Metadata/plate_1.png" Id="rel-4" Type="http://schemas.bambulab.com/package/2021/cover-thumbnail-middle"/><Relationship Target="/Metadata/plate_1_small.png" Id="rel-5" Type="http://schemas.bambulab.com/package/2021/cover-thumbnail-small"/></Relationships>\n'],
    ['Metadata/_rels/model_settings.config.rels','<?xml version="1.0" encoding="UTF-8"?>\n<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Target="/Metadata/plate_1.gcode" Id="rel-1" Type="http://schemas.bambulab.com/package/2021/gcode"/></Relationships>\n'],
    ['Metadata/model_settings.config',`<?xml version="1.0" encoding="UTF-8"?>\n<config><plate>\n${meta({plater_id:1,plater_name:'SAAM',locked:false,filament_map_mode:'Manual',filament_maps:map,filament_volume_maps:0,gcode_file:GCODE,thumbnail_file:'Metadata/plate_1.png',thumbnail_no_light_file:'Metadata/plate_no_light_1.png',top_file:'Metadata/top_1.png',pick_file:'Metadata/pick_1.png',pattern_bbox_file:'Metadata/plate_1.json'})}\n</plate></config>\n`],
    ['Metadata/slice_info.config',`<?xml version="1.0" encoding="UTF-8"?>\n<config><header><header_item key="X-BBL-Client-Type" value="slicer"/><header_item key="X-BBL-Client-Version" value="SAAM-${xml(c.release.generatorVersion)}"/></header><plate>\n${meta({index:1,extruder_type:'0 0',nozzle_volume_type:'0 0',printer_model_id:'O1D',nozzle_diameters:'0.4,0.4',timelapse_type:0,prediction:seconds,weight:fmt(weight,3),pause_count:0,first_layer_time:0,outside:false,support_used:false,label_object_enabled:false,support_material_on_wipe_tower:false,enable_filament_dynamic_map:false,has_filament_switcher:false,filament_maps:map,limit_filament_maps:0})}\n<object identify_id="1" name="SAAM part" skipped="false"/><filament id="1" tray_info_idx="GFA00" type="PLA" color="#28A090" used_m="${fmt(filament/1000,4)}" used_g="${fmt(weight,3)}" group_id="${tool}" nozzle_diameter="0.40" volume_type="Standard" used_for_object="true" used_for_support="false" total_load_time="26.00" total_unload_time="0.00"/><nozzle id="${tool}" extruder_id="${map}" nozzle_diameter="0.4" volume_type="Standard"/><layer_filament_lists><layer_filament_list filament_list="0" layer_ranges="0 ${c.layers-1}"/></layer_filament_lists></plate></config>\n`],
    ['Metadata/filament_sequence.json',json({plate_1:{nozzle_sequence:[tool],optimal_assignment:[0],sequence:[1]}})],
    ['Metadata/project_settings.config',json({printer_model:'Bambu Lab H2D',printer_settings_id:'Bambu Lab H2D 0.4 nozzle',gcode_flavor:'marlin',curr_bed_type:'Textured PEI Plate',physical_extruder_map:['1','0'],filament_map:[String(map)],filament_map_mode:'Manual',filament_nozzle_map:[String(tool)],nozzle_diameter:['0.4','0.4'],nozzle_volume_type:['Standard','Standard'],filament_diameter:['1.75'],filament_type:['PLA'],filament_ids:['GFA00'],filament_colour:['#28A090'],filament_density:['1.26'],filament_flow_ratio:['1'],nozzle_temperature:[String(plan.setup.nozzleC)],nozzle_temperature_initial_layer:[String(plan.setup.nozzleC)],hot_plate_temp:[String(plan.setup.bedC)],hot_plate_temp_initial_layer:[String(plan.setup.bedC)],chamber_temperatures:['0'],layer_height:String(plan.process.layerMm),initial_layer_print_height:String(plan.process.firstLayerMm),enable_arc_fitting:'0'})]
  ]);
  for(const [name,size] of [['plate_1',256],['plate_1_small',128],['plate_no_light_1',256],['top_1',256],['pick_1',256]])entries.set(`Metadata/${name}.png`,thumbnail(program.moves,c.bounds,size));
  return entries;
}

// Fresh toolpath thumbnail from the interpreted output, never the user's
// reference object's thumbnail. This is a schematic top view, not geometry.
function thumbnail(moves,bounds,size){
  const pixels=Buffer.alloc(size*size*4);for(let i=0;i<pixels.length;i+=4){pixels[i]=24;pixels[i+1]=30;pixels[i+2]=35;pixels[i+3]=255;}
  const span=Math.max(bounds.max[0]-bounds.min[0],bounds.max[1]-bounds.min[1]),scale=(size-20)/span;
  const project=p=>[Math.round(10+(p[0]-bounds.min[0])*scale),Math.round(size-11-(p[1]-bounds.min[1])*scale)];
  for(const m of moves){if(!m.extruding)continue;const a=project(m.from),b=project(m.to),n=Math.max(1,Math.abs(b[0]-a[0]),Math.abs(b[1]-a[1]));for(let j=0;j<=n;j++){
    const x=Math.round(a[0]+(b[0]-a[0])*j/n),y=Math.round(a[1]+(b[1]-a[1])*j/n);if(x<0||y<0||x>=size||y>=size)continue;
    const k=(y*size+x)*4;pixels[k]=40;pixels[k+1]=160;pixels[k+2]=144;
  }}
  const raw=Buffer.alloc(size*(1+size*4));for(let y=0;y<size;y++)pixels.copy(raw,y*(1+size*4)+1,y*size*4,(y+1)*size*4);
  const chunk=(name,data)=>{const type=Buffer.from(name),length=Buffer.alloc(4),crc=Buffer.alloc(4);length.writeUInt32BE(data.length);crc.writeUInt32BE(crc32(Buffer.concat([type,data])));return Buffer.concat([length,type,data,crc]);};
  const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(size);ihdr.writeUInt32BE(size,4);ihdr[8]=8;ihdr[9]=6;
  return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',ihdr),chunk('IDAT',deflateSync(raw,{level:9})),chunk('IEND',Buffer.alloc(0))]);
}
