// Discoverable patch schemas. The shared recipe validators own exact complete
// records; optional properties here permit the same partial edits as bulk patches.
import {z} from 'zod';
import {FILL_PATTERNS} from '../../../core/region/fill-patterns.mjs';
import {CLADDING_PATTERNS} from '../../../core/path/surface-courses.mjs';
const number=z.number().finite(),positive=number.positive(),names=z.array(z.string()),xyz=z.tuple([number,number,number]),uv=z.tuple([number,number]);
const weighted=z.union([xyz,z.tuple([number,number,number,positive])]);
export const patchSchema=z.object({name:z.string(),degreeU:z.number().int().min(1).max(5),degreeV:z.number().int().min(1).max(5),controlPoints:z.array(z.array(weighted)),knotsU:z.array(number).nullable().optional(),knotsV:z.array(number).nullable().optional()}).describe('Named NURBS patch; control-net rows along U, points along V; optional full knot vectors.');
export const geometrySchema=z.lazy(()=>z.object({shape:z.enum(['spline','mesh','blob-field','boolean','assembly','text','heat-set','gridfinity']),patches:z.array(patchSchema).optional(),vertices:z.array(xyz).optional(),triangles:z.array(z.tuple([z.number().int(),z.number().int(),z.number().int()])).optional(),source:z.unknown().optional(),operation:z.enum(['union','difference','intersection']).optional(),operands:z.array(geometrySchema).optional(),parts:z.array(z.object({id:z.string(),geometry:geometrySchema,xMm:number,yMm:number,zMm:number})).optional()}).passthrough()).describe('Same authored geometry record as recipe geometry; derived mesh forms retain their feature/provenance fields.');
const blob=z.object({schema:z.literal('saam-blob-field/1'),points:z.array(z.object({positionMm:xyz,reachMm:positive,strength:number})),threshold:positive});
export const fieldSchema=z.lazy(()=>z.object({
  kind:z.enum(['periodic','noise','bumps','ramp','blob','solid-distance','transfer','add','multiply']).optional(),
  axis:xyz.describe('Nonzero sampling direction in selected frame.').optional(),periodMm:z.union([positive,xyz]).describe('Periodic scalar period; bumps XYZ lattice periods. Slice frame uses native UV units.').optional(),
  phaseRad:number.optional(),waveform:z.enum(['sine','triangle','square']).optional(),transitionFraction:number.min(0).max(.5).describe('Square transition width as fraction of cycle: default0.05 for displacement/tilt, zero for scalar channels.').optional(),cellMm:positive.optional(),seed:z.number().int().optional(),
  radiusMm:positive.optional(),originMm:xyz.optional(),fromMm:number.optional(),toMm:number.optional(),field:blob.optional(),
  geometry:geometrySchema.optional(),toleranceMm:positive.describe('Solid-distance tessellation tolerance, not exact native distance.').optional(),signed:z.boolean().optional(),
  source:fieldSchema.optional(),sources:z.array(fieldSchema).optional(),input:z.tuple([number,number]).describe('Increasing transfer input range; outside clamps.').optional(),output:z.tuple([number,number]).optional()
}).strict()).describe('periodic: axis,periodMm,phaseRad,waveform?; noise:cellMm,seed; bumps:periodMm XYZ,radiusMm,originMm; ramp:axis,fromMm,toMm; blob:field; solid-distance:geometry,toleranceMm,signed; transfer:source,input,output; add/multiply:sources.');
const modulationRecordSchema=z.object({id:z.string().optional(),assignments:names.nullable().optional(),roles:names.nullable().optional(),
  channel:z.enum(['displacement','flow','width','speed','tilt']).optional(),amplitude:number.describe('Displacement mm; tilt degrees; other channels multiply by 1+amplitude*field.').optional(),
  direction:z.union([xyz,z.enum(['lateral','stack'])]).optional(),frame:z.enum(['world','slice','curve']).describe('World XYZ; slice native UV+basis; curve arc length, normalized parameter, normal coordinate.').optional(),
  layers:z.object({from:z.number().int().nonnegative(),to:z.number().int().nonnegative()}).nullable().describe('Inclusive producer-family layer indices, zero based.').optional(),topN:z.number().int().positive().nullable().optional(),phasePerLayerRad:number.optional(),
  field:fieldSchema.optional(),sampleStepMm:positive.optional(),tolerance:positive.optional()
}).strict();
export const surfaceSchema=z.object({kind:z.enum(['horizontal','plane','roof','spline','patch','mesh-strip']).optional(),origin:xyz.optional(),normal:xyz.optional(),xAxis:xyz.optional(),offsetMm:number.optional(),patch:z.union([patchSchema,z.string()]).optional(),part:z.string().nullable().optional(),periodicU:z.boolean().optional(),normalSide:z.union([z.literal(1),z.literal(-1)]).optional(),uvBounds:z.tuple([uv,uv]).optional(),rows:z.array(z.array(z.number().int())).optional()}).strict();
const process=z.object({...Object.fromEntries(['firstLayerMm','layerMm','lineWidthMm','planarSpeedMmS','firstLayerSpeedMmS'].map(k=>[k,positive.optional()])),fanPercent:number.min(0).max(100).optional()}).strict();
const nurbs=z.object({degree:z.number().int().positive(),knots:z.array(number),controlPoints:z.array(z.union([uv,xyz])),weights:z.array(positive).optional()});
const profile=z.array(z.tuple([number,z.union([number,xyz])]));
const reference=z.object({kind:z.enum(['patch','slice','sleeve']),part:z.string().nullable().optional(),name:z.string().optional(),assignment:z.string().optional(),index:z.number().int().optional()}).strict();
const curve=z.object({points:z.array(xyz).optional(),nurbs:nurbs.optional(),uv:z.object({reference,points:z.array(uv).optional(),nurbs:nurbs.optional(),normalMm:number.optional()}).optional(),text:z.object({fontId:z.string(),text:z.string(),heightMm:positive,beadRangeMm:z.tuple([positive,positive]),origin:xyz,weight:z.enum(['light','regular','bold']).optional(),stemRatio:positive.optional(),letterSpacingMm:number.optional(),align:z.enum(['left','center','right']).optional(),chain:z.boolean().optional(),spacingFactor:positive.optional(),onInfeasible:z.enum(['reduce','error']).optional()}).optional(),closed:z.boolean(),role:z.string().optional(),beadWidthMm:positive.optional(),heightMm:positive.optional(),speedMmS:positive.optional(),flowMultiplier:positive.optional(),courses:z.array(z.number().int()).optional(),
  vary:z.object(Object.fromEntries(['beadWidthMm','heightMm','flowMultiplier','speedMmS','toolAxis','toolUp','rotaryDeg'].map(k=>[k,profile.optional()]))).optional(),widthRule:z.object({widthMm:positive,beadRangeMm:z.tuple([positive,positive]),spacingFactor:positive.optional(),initialNormal:xyz.optional()}).optional(),sampleStepMm:positive.optional(),toleranceMm:positive.optional()});
const volume=z.object({kind:z.enum(['slab','geometry','outline','support','surface-domain']),fromMm:number.optional(),toMm:number.nullable().optional(),geometry:geometrySchema.optional(),footprint:z.array(z.array(uv)).optional(),contactZMm:number.optional(),topGapMm:number.optional(),xyGapMm:number.optional(),loopsUv:z.array(z.array(uv)).optional(),fromLayer:z.number().int().optional(),toLayer:z.number().int().optional()}).strict();
const values=z.union([number,z.array(number)]),sleevePath=z.object({points:z.array(uv),beadHeightMm:values,offsetMm:values.optional()});
const sleevePattern=z.object({paths:z.array(sleevePath).optional(),advance:uv.optional(),repeats:z.number().int().positive(),tile:sleevePath.optional(),cellsPerTurn:z.number().int().positive().optional(),courseRiseMm:positive.optional(),tiltDeg:number.optional()});
const bridge=z.object({id:z.string(),mode:z.enum(['alternating','one-way']),rails:z.tuple([z.array(xyz),z.array(xyz)]),speedMmS:positive,attachmentSpeedMmS:positive,flowMultiplier:positive,overlapMm:positive,pressMm:number.nonnegative(),jogMm:number.nonnegative(),leadInMm:number.nonnegative(),supportBridge:z.string().optional(),maxSegmentMm:positive.optional(),endAttachment:z.object({flowMultiplier:positive,jogMm:number.nonnegative(),overlapMm:positive,pressMm:number.nonnegative(),speedMmS:positive}).optional()});
const injectionPoint=z.object({point:xyz.describe('XYZ before recipe XY placement; no component transform.'),volumeMm3:positive.describe('Stationary deposited material volume in mm³.'),flowMm3S:positive.describe('Material flow rate, within selected material limit.'),holdSeconds:number.nonnegative().describe('Dwell after extrusion.'),approachMm:number.nonnegative().describe('Vertical nondepositing descent from this distance above the point.')}).strict();
const sliceRecordSchema=z.object({id:z.string().optional(),construction:z.enum(['skin','fronts','sleeve','rim','cladding','curves','bridges','inject']).optional(),part:z.string().nullable().optional(),preset:z.enum(['brim','support']).nullable().optional(),filament:z.number().int().nonnegative().nullable().optional(),process:process.nullable().optional(),after:names.optional(),
  points:z.array(injectionPoint).optional(),nozzleC:positive.nullable().describe('Inject operation temperature; null retains selected material setup, non-null restores setup afterward.').optional(),
  loops:z.number().int().nonnegative().optional(),fillDensity:number.optional(),fillPattern:z.enum(FILL_PATTERNS).optional(),fillAnglesDeg:z.array(number).optional(),rotateFill:z.boolean().optional(),solidTop:z.number().int().optional(),solidBottom:z.number().int().optional(),fillOverlap:number.optional(),spacingFactor:positive.optional(),sampleStepMm:positive.optional(),within:z.array(volume).optional(),surface:surfaceSchema.nullable().optional(),stack:z.object({firstLayerMm:positive.optional(),layerMm:positive.optional(),direction:xyz.describe('Default plane normal or mean normal over the entire spline reference domain.').optional()}).nullable().optional(),
  layers:z.number().int().positive().optional(),pitchMm:positive.describe('Target mean normal gap; translation distance is derived over the full reference.').optional(),strokeAngleDeg:number.optional(),surveyStepMm:positive.optional(),maxAngleDegOverride:number.nullable().optional(),supportFrom:z.string().nullable().optional(),
  domainUv:z.array(z.array(uv)).optional(),seedUv:z.array(z.array(uv)).optional(),afterParts:z.array(z.string().nullable()).optional(),beforeParts:z.array(z.string().nullable()).optional(),reason:z.string().optional(),lineSpacingMm:positive.optional(),beadHeightMm:positive.optional(),speedMmS:positive.optional(),fanPercent:number.optional(),toleranceMm:positive.optional(),propagationStepMm:positive.optional(),
  curves:z.array(curve).optional(),repeat:z.union([z.object({count:z.number().int().positive().optional(),translation:xyz.optional()}),z.object({family:z.string().optional(),indices:z.array(z.number().int()).nullable().optional()})]).nullable().optional(),
  join:z.object({mode:z.literal('spiral'),levelEnd:z.boolean()}).nullable().optional(),fillOrder:z.object({kind:z.literal('fronts'),seedUv:z.array(z.array(uv)).nullable(),lineSpacingMm:positive,propagationStepMm:positive,toleranceMm:positive}).nullable().optional(),dependencies:z.object({afterParts:z.array(z.string().nullable()),beforeParts:z.array(z.string().nullable()),after:names}).optional(),description:z.string().optional(),bridges:z.array(bridge).optional(),maxExcursionMm:positive.optional(),
  zStartMm:number.optional(),zEndMm:number.nullable().optional(),endTransition:z.enum(['level','spiral']).optional(),pattern:z.union([z.enum(CLADDING_PATTERNS),sleevePattern]).nullable().optional(),pathMode:z.enum(['continuous','segmented']).optional(),meshSleeve:z.object({fidelity:number,contactSide:z.enum(['inside','outside']),circumferentialControls:z.number().int(),heightControls:z.number().int(),detailToleranceMm:positive}).nullable().optional(),boundaryToleranceMm:positive.optional(),minFeatureMm:positive.optional(),sleeveToleranceMm:number.nonnegative().optional(),
  source:z.string().nullable().optional(),steps:z.array(z.number().int().nonnegative()).optional(),shells:z.number().int().positive().optional(),normalMm:positive.describe('Cladding normal course thickness; obsolete for skin (use pitchMm).').optional(),tiltDeg:number.optional(),offsetTightness:number.optional()
}).strict().describe('General assignment patch. Common factories fill defaults on add; edit merges objects and replaces arrays. Exact shared recipe validation follows.');

// Objects merge recursively, arrays replace completely. Mirror those semantics
// in the discovery schema without weakening each replacement array's records.
function objectPatch(schema,cache=new Map(),patch=true){
  if(cache.get(schema)?.has(patch))return cache.get(schema).get(patch);
  let result=schema;
  if(schema instanceof z.ZodLazy)result=z.lazy(()=>objectPatch(schema.unwrap(),cache,patch));
  else if(schema instanceof z.ZodObject){
    result=schema.extend(Object.fromEntries(Object.entries(schema.shape).map(([key,value])=>{const child=objectPatch(value,cache,patch);return [key,patch?child.optional():child];})));
    if(!(schema.def.catchall instanceof z.ZodUnknown))result=result.strict();
  }
  else if(schema instanceof z.ZodArray)result=z.array(objectPatch(schema.element,cache,false));
  else if(schema instanceof z.ZodOptional)result=objectPatch(schema.unwrap(),cache,patch).optional();
  else if(schema instanceof z.ZodNullable)result=objectPatch(schema.unwrap(),cache,patch).nullable();
  else if(schema instanceof z.ZodUnion)result=z.union(schema.options.map(option=>objectPatch(option,cache,patch)));
  if(schema.description)result=result.describe(schema.description);
  if(!cache.has(schema))cache.set(schema,new Map());cache.get(schema).set(patch,result);return result;
}
export const slicePatchSchema=objectPatch(sliceRecordSchema);
export const modulationPatchSchema=objectPatch(modulationRecordSchema);
export const draftFamilySchema=slicePatchSchema.pick({id:true,part:true,preset:true,process:true,within:true,surface:true,stack:true,sampleStepMm:true});
