import {createAssemblyRenderer} from './render.mjs';
import {createProjection} from '/studio/camera.mjs';
import {defaults,validateDesign,buildModel} from './model.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelector('.layers').open=innerWidth>1100;
let renderer;
let design={...defaults},stage=0,airfoils=[],model,camera={yaw:-.38,tilt:.75,zoom:1,pan:[0,0]},search='';
const stages=['Use','Airfoil','Planform','Tips','Controls','Structure'];
const toast=message=>{$('toast').textContent=message;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',4000);};
try{const stored=localStorage.getItem('saam-wing-design-v1');if(stored)design=validateDesign(JSON.parse(stored));}catch{toast('The saved draft could not be loaded. Starting with a new concept.');}
const range=(key,title,min,max,step=1,unit='')=>`<label class="field"><span>${title}<output id="value-${key}">${design[key]}${unit}</output></span><input aria-label="${title}" data-key="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${design[key]}" data-unit="${unit}"></label>`;
const select=(key,title,options)=>`<label class="field"><span>${title}</span><select data-key="${key}" aria-label="${title}">${options.map(([v,t])=>`<option value="${v}" ${design[key]===v?'selected':''}>${t}</option>`).join('')}</select></label>`;
const field=(key,title,type='text')=>`<label class="field"><span>${title}</span><input data-key="${key}" aria-label="${title}" type="${type}" value="${esc(design[key])}" ${key==='name'?'maxlength="100"':''}></label>`;
const check=(key,title)=>`<label><input data-key="${key}" type="checkbox" ${design[key]?'checked':''}> ${title}</label>`;
const intro=(title,prompt)=>`<h3>${title}</h3><div class="prompt">${prompt}</div>`;
function panel(){
  $('stages').innerHTML=stages.map((name,i)=>`<button data-stage="${i}" class="${stage===i?'active':''}" aria-current="${stage===i?'step':'false'}"><span>${i+1}</span>${name}</button>`).join('');
  const parts=[
    ()=>intro('What should this craft do?','Start with its purpose. These choices shape the conversation and the airfoil shortlist; they do not establish flight performance.')+field('name','Design name')+select('application','Aircraft type',[['trainer','Everyday / trainer'],['glider','Glider'],['aerobatic','Aerobatic'],['flying-wing','Flying wing']])+select('priority','Flight priority',[['balanced','Balanced handling'],['slow','Slow flight / lift'],['endurance','Endurance / gliding'],['speed','Speed']])+range('mass','Target flight mass',.1,30,.1,' kg')+range('speed','Cruise speed',5,70,1,' m/s')+`<label class="field"><span>Tell your agent more</span><textarea data-key="notes" maxlength="3000" placeholder="Payload, launch method, handling, size constraints…">${esc(design.notes)}</textarea></label><p class="hint">Notes are saved with the design for your conversation with the agent. This prototype does not contain an AI chat service.</p>`,
    ()=>intro('Choose a starting section.','Explore source-backed shapes, then discuss the tradeoffs with your agent. Cards are ordered by broad application tags, not predicted flight performance.')+`<input id="foil-search" type="search" aria-label="Search airfoils" placeholder="Search name or family…" value="${esc(search)}"><p class="hint">6 UIUC profiles · geometry data only<br>Performance polars are not loaded in this prototype.</p><div class="foil-list" id="foil-list"></div>`,
    ()=>intro('Give the wing its planform.','Set the overall proportions. Your selected airfoil is lofted across the span; sweep, dihedral and washout update the model together.')+range('span','Wing span',400,2400,20,' mm')+range('root','Root chord',100,450,5,' mm')+range('taper','Tip / root chord',.3,1,.05)+range('sweep','Quarter-chord sweep',0,25,1,'°')+range('dihedral','Dihedral',0,12,1,'°')+range('twist','Tip twist',-6,4,.5,'°')+`<div class="mini-note">Negative tip twist is washout. Tip treatment is next, before laying out the controls.</div>`,
    ()=>intro('How should the tips end?','Choose the outer shape first, then decide how it is built. The tip updates immediately; a separate cap shows a seam.')+select('tip','Tip shape',[['square','Squared'],['rounded','Rounded'],['tapered','Tapered'],['winglet','Upturned winglet']])+select('tipBuild','Tip construction',[['integral','Integral closure'],['cap','Separate cap'],['removable','Removable tip']])+`<p class="hint">Removable tips show locating pins. Winglets are concept geometry, not an aerodynamic optimization.</p>`,
    ()=>intro('How will the craft be controlled?','Consider roll control, slow-flight needs and the tail arrangement. Colored surfaces show their extent; use the angle slider to inspect the wing controls.')+`<div class="choice-row">${check('ailerons','Ailerons')}${check('flaps','Flaps')}</div>`+select('flapType','Flap arrangement',[['plain','Plain hinged flap'],['split','Split flap (lower surface)']])+range('controlChord','Control chord fraction',.15,.4,.01)+range('deflection','Wing control deflection',-25,40,1,'°')+select('tail','Tail arrangement',[['conventional','Conventional tail'],['v-tail','V-tail'],['none','No tail']])+`<p class="hint">Ailerons move differentially; flaps move together. Tails use NACA 0012 and provisional dimensions. Servos, hinges and horns are size-reference proxies. Slotted / translating flaps and control mixing are not modeled.</p>`,
    ()=>intro('How will it hold together?','Choose reinforcement and fuselage attachment as one strategy. Turn on wireframe to see the members and the hollow rib layout.')+select('reinforcement','Reinforcement location',[['tubes','Internal hollow tubes'],['embedded','Near-surface rods']])+range('sparCount','Members per half-wing',1,3,1)+range('sparDiameter','Tube outside diameter',4,20,1,' mm')+range('skin','Preview skin thickness',.6,3,.1,' mm')+select('bond','Installation method',[['glue','Glued in'],['struder','Welded in with Struder']])+select('mount','Fuselage attachment',[['bolts','Top-mounted · bolts'],['bands','Top-mounted · rubber bands'],['telescopic','Tube-in-tube joiners']])+`<p class="hint">Joiners stay straight and unswept. Mounts, seating and clearances are concept features. Welding is saved as intent, not a generated process.</p><button id="copy-brief">Copy brief for your agent</button>`
  ];
  $('panel').innerHTML=parts[stage]();$('panel').scrollTop=0;$('back').disabled=stage===0;$('next').textContent=stage===5?'Save design ↗':'Continue →';
  if(stage===1)renderFoils();
}
function profileSvg(f){const points=[...f.profile.upper.toReversed(),...f.profile.lower].map(([x,y])=>`${10+x*260},${28-y*180}`).join(' ');return `<svg viewBox="0 0 280 50" aria-label="${esc(f.name)} section"><line x1="8" y1="28" x2="272" y2="28" stroke="#d7dfd4" stroke-dasharray="3 3"/><polygon points="${points}" fill="#dce8df" stroke="#4c7160" stroke-width="1.2"/></svg>`;}
function renderFoils(){
  const score=f=>f.tags.includes(design.application)+f.tags.includes(design.priority);
  const items=airfoils.filter(f=>(f.name+' '+f.family).toLowerCase().includes(search.toLowerCase())).toSorted((a,b)=>score(b)-score(a));
  $('foil-list').innerHTML=items.length?items.map(f=>`<div><button class="foil-card ${design.foil===f.id?'selected':''}" data-foil="${f.id}" aria-pressed="${design.foil===f.id}"><div class="foil-top"><b>${f.name}</b><span>${design.foil===f.id?'SELECTED':'VIEW SECTION'}</span></div>${profileSvg(f)}<div class="foil-spec"><span>${(100*f.thickness).toFixed(1)}% thick</span><span>${(100*f.camber).toFixed(1)}% camber</span><span>${(design.root*f.thickness).toFixed(1)} mm at root</span></div><p>${f.note}</p><div class="evidence">Coordinates: UIUC · Performance: not loaded</div></button><a class="source-link" target="_blank" rel="noopener" href="${f.source}">Source coordinates ↗</a></div>`).join(''):'<div class="empty">No matching profile in the six-airfoil starter library.</div>';
}
function persist(){try{localStorage.setItem('saam-wing-design-v1',JSON.stringify(design));$('save-state').textContent='Draft saved locally';}catch{$('save-state').textContent='Use Save design to keep changes';}}
function rebuild(){
  try{const next=buildModel(design,airfoils.find(f=>f.id===design.foil).profile,airfoils.find(f=>f.id==='n0012').profile);model=next;updateSummary();draw();persist();}catch(e){toast(e.message);}
}
function updateSummary(){
  const f=airfoils.find(f=>f.id===design.foil),area=design.span*design.root*(1+design.taper)/2/1e6,re=design.speed*design.root/1000/1.5e-5;
  $('design-title').textContent=design.name||'Untitled wing';$('design-summary').textContent=`${f.name} · ${design.span} mm span · ${design.tip} tips`;
  $('stats').innerHTML=`<div class="stat"><small>Wing area</small><strong>${(area*100).toFixed(1)} <span>dm²</span></strong></div><div class="stat"><small>Aspect ratio</small><strong>${((design.span/1000)**2/area).toFixed(1)}</strong></div><div class="stat"><small>Root Reynolds¹</small><strong>${Math.round(re/1000)}<span>k</span></strong></div><div class="stat"><small>Wing loading</small><strong>${(design.mass*1000/(area*100)).toFixed(0)} <span>g/dm²</span></strong></div>`;
  $('stats').title='Planform metrics exclude tip extensions. ¹ Assumes kinematic viscosity 1.5 × 10⁻⁵ m²/s; no aerodynamic solver.';
  $('warnings').innerHTML=model.warnings.slice(0,2).map(w=>`<p>${esc(w)}</p>`).join('');
}
function visible(part){const g=part.group;if(g==='interior')return false;if(['servos','hinges','horns'].includes(g))return $('hardware').checked&&$(g).checked;if(g==='attachment')return $('hardware').checked;if(['spars','ribs','reference'].includes(g))return $(g).checked;return true;}
function draw(){
  if(!model)return;const canvas=$('model'),rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=rect.width,h=rect.height;
  if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);
  const projection=createProjection(model.bounds,w,h,camera.yaw,camera.tilt,camera.zoom,camera.pan,true);
  ctx.strokeStyle='#b9c7b633';ctx.lineWidth=.7;
  for(let i=-1800;i<=1800;i+=100){for(const line of [[[i,-900,-65],[i,1200,-65]],[[-1800,i,-65],[1800,i,-65]]]){const [a,b]=line.map(projection);ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke();}}
  renderer.draw(model.parts.filter(visible),projection,w,h,dpr,$('wire').checked);
  ctx.drawImage(renderer.canvas,0,0,w,h);
  ctx.fillStyle='#6c7a68';ctx.font='10px -apple-system, sans-serif';ctx.fillText('X · span',23,h-48);
}
$('stages').onclick=e=>{const b=e.target.closest('[data-stage]');if(b){stage=+b.dataset.stage;panel();}};
$('back').onclick=()=>{stage=Math.max(0,stage-1);panel();};$('next').onclick=()=>{if(stage===5)save();else{stage++;panel();}};
$('panel').addEventListener('input',e=>{
  const key=e.target.dataset.key;if(e.target.id==='foil-search'){search=e.target.value;renderFoils();return;}if(!key)return;
  const value=e.target.type==='checkbox'?e.target.checked:e.target.type==='range'||e.target.type==='number'?+e.target.value:e.target.value;
  try{const next=validateDesign({...design,[key]:value});const nextModel=buildModel(next,airfoils.find(f=>f.id===next.foil).profile,airfoils.find(f=>f.id==='n0012').profile);design=next;model=nextModel;const out=$('value-'+key);if(out)out.textContent=value+(e.target.dataset.unit||'');updateSummary();draw();persist();}catch(error){toast(error.message);}
});
$('panel').onclick=e=>{const foil=e.target.closest('[data-foil]');if(foil){design.foil=foil.dataset.foil;rebuild();renderFoils();}if(e.target.id==='copy-brief')navigator.clipboard.writeText(`Please help refine this SAAM wing concept. Current design:\n${JSON.stringify(design,null,2)}\nNext discuss structural fit and attachment. This is concept geometry, not a validated aircraft.`).then(()=>toast('Design brief copied. Paste it into your agent conversation.')).catch(()=>toast('Clipboard unavailable. Save the design JSON to share it.'));};
for(const id of ['wire','spars','ribs','hardware','servos','hinges','horns','reference'])$(id).onchange=draw;
let drag=null;$('model').onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,pan:e.shiftKey||e.button===2};$('model').setPointerCapture(e.pointerId);};$('model').onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(drag.pan){camera.pan[0]+=dx;camera.pan[1]+=dy;}else{camera.yaw+=dx*.008;camera.tilt=Math.max(-1.55,Math.min(1.55,camera.tilt+dy*.008));}drag.x=e.clientX;drag.y=e.clientY;draw();};$('model').onpointerup=()=>drag=null;$('model').onpointercancel=()=>drag=null;$('model').oncontextmenu=e=>e.preventDefault();$('model').addEventListener('wheel',e=>{e.preventDefault();camera.zoom=Math.max(.35,Math.min(5,camera.zoom*Math.exp(-e.deltaY*.001)));draw();},{passive:false});
$('model').onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();camera.yaw+=(e.key==='ArrowRight'?.1:e.key==='ArrowLeft'?-.1:0);camera.tilt+=(e.key==='ArrowUp'?.1:e.key==='ArrowDown'?-.1:0);draw();}};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const view=b.dataset.view;[camera.yaw,camera.tilt]=({perspective:[-.38,.75],top:[0,Math.PI/2],front:[0,0],side:[Math.PI/2,0]})[view];draw();});$('fit').onclick=()=>{camera.zoom=1;camera.pan=[0,0];draw();};new ResizeObserver(draw).observe($('model'));
function save(){const blob=new Blob([JSON.stringify(design,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(design.name||'wing-design').replace(/[^a-z0-9_-]/gi,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('save').onclick=save;$('load').onclick=()=>$('file').click();$('file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>100000)throw Error('Design file is too large.');const next=validateDesign(JSON.parse(await file.text()));const nextModel=buildModel(next,airfoils.find(f=>f.id===next.foil).profile,airfoils.find(f=>f.id==='n0012').profile);design=next;model=nextModel;panel();rebuild();toast('Design opened.');}catch(error){toast(error.message);}finally{e.target.value='';}};
try{renderer=createAssemblyRenderer();const response=await fetch('/api/airfoils');if(!response.ok)throw Error('Airfoil library could not be loaded.');airfoils=await response.json();panel();rebuild();}catch(error){$('panel').textContent=error.message;}
