export const TOUR_VERSION=1; // Saved tour marker format; independent of the lesson deck.
export const TOUR_DECK_VERSION=5;
export const TOUR_LESSONS={geometry:0,roof:1,open:2,import:3,playback:4,settings:5,setup:6,export:7};
export const TOUR_DEMOS=[
  {id:'starter',title:'Fin block',subtitle:'A simple part with one bold feature'},
  {id:'surface-drape',title:'Wavy roof',subtitle:'Let layers follow the shape'},
  {id:'nudge-cup',title:'Nudge Cup',subtitle:'Combine patterns in one useful part'},
  {id:'wavy-denso',title:'Wavy DENSO',subtitle:'Print in more than one direction'}
];
export const TOUR_STEPS=[
  {demo:'starter',tab:'geometry',gate:'geometry',title:'Your words change the shape',body:'This little block has a raised fin. Ask your agent to make the fin taller, wider or shorter. This lesson introduces changing a shape through conversation.',try:'Send your request in chat. Next unlocks when your agent updates the geometry.'},
  {demo:'surface-drape',tab:'geometry',title:'Try a more interesting surface',body:'This wavy roof combines rolling curves with a downhill tilt. The same conversation can shape a simple block or a flowing surface.',try:'Ask your agent to change this roof, or continue. Your edits to both parts are saved.'},
  {tab:'geometry',gate:'open',highlight:'open-print',title:'Choose a saved print',body:'Open print lets you switch between your parts. Both geometries are saved, including any changes you requested.',try:'Click Open print and choose either part. You will continue the tour with that selected shape.'},
  {tab:'geometry',highlight:'import-stl',title:'Bring your own model next time',body:'Import STL opens a model from your computer in normal Studio. It is unavailable during this guided tour so the remaining lessons stay with the print you chose.',try:'Notice Import STL above, then continue with this part. You can import your own model after finishing or exiting the tour.'},
  {tab:'toolpath',gate:'playback',highlight:'play',title:'Watch the material go down',body:'The preview starts at a useful point chosen by your agent, or near the beginning if none was supplied. Press Play to see how material is deposited.',try:'Next unlocks as soon as playback starts. You can keep watching, scrub anywhere or change the playback speed.'},
  {tab:'toolpath',gate:'settings',title:'Change how this part prints',body:'The shape is set; now the toolpath decides how it is built. Your agent will suggest a few useful changes for strength, finish, print time or material use, based on this print.',try:'Choose one in chat, or ask for another printing change. Next unlocks after the updated toolpath finishes loading.'},
  {tab:'toolpath',highlight:'print-setup',title:'Match this file to your printer',body:'Check the highlighted printer and material against the machine and filament you plan to use. These choices control the file format, temperatures and how material is deposited.',try:'This tour started with Ultimaker S5 and PLA. If either is different, tell your agent now and review the updated toolpath. Otherwise, continue. On future prints your agent establishes these choices before toolpath view.'},
  {tab:'toolpath',highlight:'confirm',title:'Take the file to your printer',body:'Confirm settings & export approves the displayed settings and toolpath, prepares and downloads the machine file, and completes this tour. Usually you copy it to a USB drive and plug that directly into the printer.',try:'Download the file to complete the tour. It is ready for the selected printer—do not slice it again in another printing app. You can still Exit tour at any time.'}
];
export function tourAgentInstruction(data){
  if(data.completed)return 'Immediately send ordinary chat text congratulating the participant on finishing the tour and downloading the file. In that same text, offer help with any difficulties printing the file and ask what she wants to make next. Never use a question box, form or request-user-input tool for this message. Send the chat text before status checks, logging, browser inspection or another listener call. If the client permits questions only in a final response, send this as the final chat response.';
  if(!data.active)return null;
  if(data.step===TOUR_LESSONS.settings)return 'In chat, briefly teach that the toolpath controls how the confirmed shape is built. Immediately offer two or three concrete toolpath or process changes appropriate to the current recipe and choices already made, giving each option’s likely effect on strength, finish, print time or material use in plain language. Use known context; if essential context is missing, make at most one current-print read. Do not suggest geometry changes or list geometry as an option. Ask the participant to choose one or propose another printing change. Send this guidance before another listener wait, status check, browser inspection or unrelated request bookkeeping. If the participant independently asks for geometry, apply it and follow the normal confirmation flow; any requested geometry or printing change satisfies this lesson once its current toolpath is displayed. Do not pick for the participant or repeat a settled choice.';
  if(data.step===0)return 'Studio introduces the part and asks for a geometry change. Wait for the participant to make that request; do not add a chat introduction, question or instruction. Then apply the requested edit to the active tour print with adjust. Do not approve it or remove its tour marker.';
  if(data.step===TOUR_LESSONS.playback&&!data.startAt)return 'Choose a sparse-infill layer from the existing toolpath if one is available; otherwise retain Studio’s fallback. Do not edit or regenerate the print just to choose a viewing position. Do this silently; Studio provides the Play instruction. Proactive chat guidance begins at the designated change-suggestion lesson.';
  return null;
}
