import {dobotGeometry,dobotForward,dobotInverse} from '/core/machine/dobot-kinematics.mjs';
const $=id=>document.getElementById(id),canvas=$('dobotScene'),ctx=canvas.getContext('2d');
let g=dobotGeometry(),q=[0,0,0,0],state=dobotForward(g,q),yaw=.7,pitch=.3,drag=null,playing=false,phase=0,last=0,zoom=1,program=null,printPlaying=false,printTime=0,printIndex=0;
for(let i=0;i<4;i++){const l=document.createElement('label');l.innerHTML=`J${i+1}<span id="v${i}">0°</span>`;const input=document.createElement('input');Object.assign(input,{id:`q${i}`,type:'range',min:g.jointLimitsDeg[i][0],max:g.jointLimitsDeg[i][1],step:.1,value:0});l.append(input);$('joints').append(l);input.oninput=()=>{playing=false;printPlaying=false;q[i]=+input.value;state=dobotForward(g,q);update();};}
for(const [i,name]of ['X','Y','Z','Yaw'].entries()){const l=document.createElement('label');l.textContent=name+(i===3?' (°)':' (mm)');const input=document.createElement('input');Object.assign(input,{id:`t${i}`,type:'number',step:.1,value:i===3?0:state.tcp[i].toFixed(3)});l.append(input);$('target').append(l);}
function solve(tcp,angle=0){const next=dobotInverse(g,{tcp,yawDeg:angle},{seed:q});if(next.valid){state=next;q=next.joints;update();return true;}else{$('status').className='status bad';$('status').textContent=next.errors.join(' · ');return false;}}
function update(){for(let i=0;i<4;i++){$('q'+i).value=q[i];$('v'+i).textContent=q[i].toFixed(1)+'°';$('t'+i).value=i===3?state.yawDeg.toFixed(3):state.tcp[i].toFixed(3);}$('status').className='status'+(state.valid?'':' bad');$('status').textContent=state.valid?`Pose passes nominal joint and singularity checks · ${state.branch} · elbow singularity margin ${state.foldMarginDeg.toFixed(1)}°`:state.errors.join(' · ');if(printPlaying&&program)$('status').textContent+=` · ${program.samples[printIndex].extruding?'EXTRUDING':'travel'} · ${printTime.toFixed(1)} s`;$('readout').innerHTML=[...state.tcp.map((v,i)=>['XYZ'[i],v.toFixed(3)+' mm']),['Tool yaw',state.yawDeg.toFixed(2)+'°'],['Tool axis','vertical, downward'],['Tool length',g.toolLengthMm+' mm']].map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join('');draw();}
function project(p){const v=[p[0]-160,p[1],p[2]-200],x=Math.cos(yaw)*v[0]-Math.sin(yaw)*v[1],d=Math.sin(yaw)*v[0]+Math.cos(yaw)*v[1],y=Math.cos(pitch)*v[2]-Math.sin(pitch)*d,s=Math.min(canvas.clientWidth/650,canvas.clientHeight/550)*zoom;return [canvas.clientWidth/2+x*s,canvas.clientHeight/2-y*s];}
function line(a,b,color,width=2){ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.moveTo(...project(a));ctx.lineTo(...project(b));ctx.stroke();}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight,d=devicePixelRatio||1;if(canvas.width!==w*d||canvas.height!==h*d){canvas.width=w*d;canvas.height=h*d;}ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);
  for(let v=-200;v<=500;v+=50){line([v,-250,0],[v,250,0],'#243845',1);line([-200,v,0],[500,v,0],'#243845',1);}
  if(program){const [bx,by]=program.bedCenterMm,bz=program.bedZMm,bed=[[bx-55,by-55,bz],[bx+55,by-55,bz],[bx+55,by+55,bz],[bx-55,by+55,bz]];for(let i=0;i<4;i++)line(bed[i],bed[(i+1)%4],'#617d8c',3);const step=Math.max(1,Math.floor(program.samples.length/4000));for(let i=step;i<program.samples.length;i+=step)if(program.samples[i].extruding)line(program.samples[i-step].tcp,program.samples[i].tcp,i<=printIndex?'#7fe6ae':'#33544f',1.3);}
  const p=state.points;for(let i=1;i<p.length;i++)line(p[i-1],p[i],i===p.length-1?'#ffa866':state.valid?'#c5d4df':'#fa9380',i===p.length-1?5:i<3?24:13);
  const off=[0,20,15];for(let i=2;i<4;i++){const a=p[i].map((v,k)=>v+off[k]),b=p[i+1].map((v,k)=>v+off[k]);line(a,b,'#60e0d1',3);line(a,p[i],'#60e0d1',2);line(b,p[i+1],'#60e0d1',2);}
  for(let i=1;i<p.length-1;i++){const [x,y]=project(p[i]);ctx.fillStyle='#14212c';ctx.strokeStyle='#60e0d1';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();ctx.stroke();}
  const tip=p.at(-1),a=state.yawDeg*Math.PI/180;line(tip,[tip[0]+25*Math.cos(a),tip[1]+25*Math.sin(a),tip[2]],'#fcca8e',3);
  ctx.fillStyle='#a1b5c5';ctx.font='12px system-ui';ctx.fillText('Drag to orbit · scroll to zoom',24,30);ctx.fillStyle='#60e0d1';ctx.fillText('MG400 · four axes · coupled parallelogram',24,52);
}
$('solve').onclick=()=>{playing=false;printPlaying=false;solve([0,1,2].map(i=>+$('t'+i).value),+$('t3').value);};$('home').onclick=()=>{playing=false;printPlaying=false;q=[0,0,0,0];state=dobotForward(g,q);update();};$('toolLength').onchange=()=>{try{g=dobotGeometry({toolLengthMm:+$('toolLength').value});program=null;printPlaying=false;$('printStatus').textContent='Tool length changed; loaded print is invalidated.';state=dobotForward(g,q);update();}catch(e){$('status').textContent=e.message;}};$('front').onclick=()=>{yaw=0;pitch=0;draw();};$('threeD').onclick=()=>{yaw=.7;pitch=.3;draw();};$('demo').onclick=()=>{printPlaying=false;playing=!playing;};
canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,yaw,pitch};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(drag){yaw=drag.yaw+(e.clientX-drag.x)*.006;pitch=Math.max(-1.2,Math.min(1.2,drag.pitch+(e.clientY-drag.y)*.006));draw();}};canvas.onpointerup=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.5,Math.min(3,zoom*Math.exp(-e.deltaY*.001)));draw();};new ResizeObserver(draw).observe(canvas);
function printFrame(){q=program.samples[printIndex].joints;state=dobotForward(g,q);$('printScrub').value=printIndex;update();}
$('printPlay').onclick=()=>{if(!program)return;playing=false;if(printIndex>=program.samples.length-1){printIndex=0;printTime=0;}printPlaying=!printPlaying;};$('printScrub').oninput=()=>{if(!program)return;playing=false;printPlaying=false;printIndex=+$('printScrub').value;printTime=program.samples[printIndex].seconds;printFrame();};
function animate(t){const dt=Math.min((t-last)/1000,.1);last=t;if(playing){phase+=dt*.5;if(!solve([280+35*Math.cos(phase),35*Math.sin(phase),270+10*Math.sin(2*phase)],0))playing=false;}if(printPlaying&&program){printTime+=dt*Number($('printSpeed').value);while(printIndex<program.samples.length-1&&program.samples[printIndex+1].seconds<=printTime)printIndex++;if(printIndex===program.samples.length-1)printPlaying=false;printFrame();}requestAnimationFrame(animate);}update();requestAnimationFrame(animate);
if(new URL(location.href).searchParams.has('preview')){try{const r=await fetch('/dobot-preview.json');if(!r.ok)throw Error('No selected Dobot print on this server');program=await r.json();if(program.schema!=='saam-dobot-kinematic-preview/1')throw Error('Unsupported Dobot preview');$('printScrub').max=program.samples.length-1;$('printStatus').textContent=`Wavy vase wall · ${program.samples.length.toLocaleString()} joint-checked samples · ${program.volumeMm3.toFixed(1)} mm³ commanded volume · ${(program.seconds/60).toFixed(1)} min nominal CP=0 timing. ${program.notice}`;printFrame();}catch(e){program=null;$('printStatus').textContent=e.message;}}
