import {geometry,inverse,orientation,matvec,add,mul,DEFAULT_GEOMETRY,carriagePoint,railBodyPoint,pairedEdgeLayout} from '/core/machine/split-delta.mjs';
import {interpretSplitDelta,exportSplitDeltaPreview,eulerRotation} from '/core/export/split-delta-player.mjs';
const $=id=>document.getElementById(id),profile=await(await fetch('/machines/split-delta.json')).json();
let config={...DEFAULT_GEOMETRY},g=geometry(config),pose={tcp:[0,0,20],tiltDeg:0,azimuthDeg:0,spinDeg:0},state,worker,report=null,program=null,playing=false,sweeping=false,index=0,lastTime=0,playbackTime=0;
let yaw=.65,pitch=.38,zoom=1,drag=null,cameraCenter=[0,0,350],loadedSource=null,displayedRailInterval=null,collisionDemo=null;
function setSource(text){loadedSource=text.length>20000?text:null;$('source').readOnly=!!loadedSource;$('source').value=loadedSource?text.split('\n').slice(0,50).join('\n')+'\n; Display shows first 50 lines; the complete loaded source is interpreted and saved.':text;}
const sourceText=()=>loadedSource??$('source').value;
const fields=[['towerRadiusMm','Pivot-track radius at mid-height',40,400],['railMountOffsetMm','Pivot stand-off from rail',0,60],['railReferenceHeightMm','Rail pivot height',0,1400],['railSeparationMm','Track pair width at pivot',10,220],['railToeDeg','Pair toe (outward +°)',-20,20],['railTiltDeg','Rail tilt (outward +°)',-15,15],['platformRadiusMm','Plate pair-center radius',10,130],['platformPairMm','Plate pivot pair spacing',10,220],['rodLengthMm','Rod length',150,1000],['rodDiameterMm','Rod diameter',4,12],['plateThicknessMm','Plate thickness',3,10],['plateRimMm','Plate rim',3,10],['platformClockDeg','Plate mounting rotation (°)',-60,60],['platformPairSkewDeg','Pivot pair skew (°)',-40,40],['toolLengthMm','Plate to nozzle tip',40,250],['operatingTiltDeg','Operating head tilt (°)',0,60],['jointConeDeg','Joint cone half-angle (°)',10,120],['railMinMm','Track minimum distance',0,1000],['railMaxMm','Track maximum distance',100,1800]];
for(const [key,label,min,max]of fields){const l=document.createElement('label');l.className='row';l.textContent=label;const input=document.createElement('input');Object.assign(input,{id:key,type:'number',min,max,value:config[key]??0,step:1});l.append(input);$('geometry').append(l);input.addEventListener('change',()=>{try{const next={...config,[key]:Number(input.value)},model=geometry(next);config=next;g=model;invalidate();update();}catch(e){$('error').textContent=e.message;}});}
const poseFields=[['x','X',-150,150,1],['y','Y',-150,150,1],['z','Z',0,400,1],['tilt','Tilt',0,60,.5],['azimuth','Tilt direction',0,360,1],['spin','Tool spin',-30,30,.5]];
for(const [key,label,min,max,step]of poseFields){const l=document.createElement('label');l.innerHTML=`${label}<span id="${key}Value"></span>`;const input=document.createElement('input');Object.assign(input,{id:key,type:'range',min,max,step,value:key==='z'?20:0});l.append(input);$('poseControls').append(l);input.oninput=()=>{playing=false;poseFromControls();};}
function poseFromControls(){pose={tcp:['x','y','z'].map(k=>Number($(k).value)),tiltDeg:+$('tilt').value,azimuthDeg:+$('azimuth').value,spinDeg:+$('spin').value};update();}
function labels(){for(const [key]of poseFields)$(key+'Value').textContent=Number($(key).value).toFixed(key==='tilt'||key==='spin'?1:0)+(key.length===1?' mm':'°');}
function invalidate(){worker?.terminate();worker=null;report=null;program=null;displayedRailInterval=null;collisionDemo=null;playing=false;$('assess').disabled=false;$('assess').textContent='Assess cylinder with angular clearance';$('assessment').textContent='Configuration changed. Reassess this cylinder.';$('saveReport').disabled=true;$('motionStatus').textContent='Configuration changed. Interpret source again.';$('error').textContent='';}
function update(){
  labels();try{state=inverse(g,pose);const reasons=[...state.errors];const layout=pairedEdgeLayout(g);if(!layout.passed)reasons.push('Invalid paired-edge layout: tower attachments interleave');if(collisionDemo&&program?.samples[index]?.line===collisionDemo.line)reasons.push(collisionDemo.message);if(state.tiltDeg>g.operatingTiltDeg+.000002)reasons.push(`${g.operatingTiltDeg}° operating tilt exceeded`);
    $('plateDimensions').textContent=`Pivot envelope Ø${(2*g.rotationScaleMm).toFixed(1)} mm. ${layout.passed?'A/B/C pairs connect to their own near edges.':'INVALID paired-edge layout: '+layout.order.join(' → ')+'.'} Top rail-body center envelope Ø${(2*Math.max(...g.railDirections.map((_,i)=>Math.hypot(...railBodyPoint(g,i,g.railMaxMm).slice(0,2))))).toFixed(1)} mm.`;
    $('poseStatus').className='status'+(reasons.length?' bad':'');$('poseStatus').textContent=reasons.length?reasons.join(' · '):'Pose passes the configured kinematic checks · upper assembly branch';
    $('elevation').textContent=state.minRodElevationDeg?.toFixed(1)+'°';$('joint').textContent=state.maxJointDeflectionDeg?.toFixed(1)+'°';
    $('conditioning').textContent=`Normalized singular-value ratio: ${state.singularRatio?.toFixed(4)??'—'} (floor ${g.minSingularRatio}). This conditioning threshold is separate from the 4° angular reserve.`;
    $('carriages').replaceChildren(...Array.from({length:6},(_,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${'ABC'[Math.floor(i/2)]}${i%2+1}</td><td>${state.heights[i]?.toFixed(2)??'unreachable'}</td>`;return tr;}));draw();
  }catch(e){$('error').textContent=e.message;}
}
const canvas=$('scene'),ctx=canvas.getContext('2d');
function project(p){const v=p.map((x,i)=>x-cameraCenter[i]),x=Math.cos(yaw)*v[0]-Math.sin(yaw)*v[1],depth=Math.sin(yaw)*v[0]+Math.cos(yaw)*v[1],y=Math.cos(pitch)*v[2]-Math.sin(pitch)*depth,z=Math.sin(pitch)*v[2]+Math.cos(pitch)*depth,scale=Math.min(canvas.clientWidth/650,canvas.clientHeight/900)*zoom;return [canvas.clientWidth/2+x*scale,canvas.clientHeight/2-y*scale,z];}
function line(a,b,color,width=1,dash=[]){const p=project(a),q=project(b);ctx.beginPath();ctx.setLineDash(dash);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.moveTo(...p.slice(0,2));ctx.lineTo(...q.slice(0,2));ctx.stroke();ctx.setLineDash([]);}
function circle3(r,z,color,dash=[]){for(let i=0;i<90;i++){const a=i*Math.PI/45,b=(i+1)*Math.PI/45;line([r*Math.cos(a),r*Math.sin(a),z],[r*Math.cos(b),r*Math.sin(b),z],color,1,dash);}}
function point(p,color,r=4){const q=project(p);ctx.beginPath();ctx.fillStyle=color;ctx.arc(q[0],q[1],r,0,Math.PI*2);ctx.fill();}
function polygon(points,fill,stroke){ctx.beginPath();for(const [i,p]of points.entries()){const q=project(p);if(i)ctx.lineTo(q[0],q[1]);else ctx.moveTo(q[0],q[1]);}ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.stroke();}
function draw(){
  const ratio=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==w*ratio||canvas.height!==h*ratio){canvas.width=w*ratio;canvas.height=h*ratio;}ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,w,h);
  for(let i=-250;i<=250;i+=50){line([i,-250,0],[i,250,0],'#263b48');line([-250,i,0],[250,i,0],'#263b48');}
  const radius=+$('diameter').value/2,height=+$('height').value;circle3(radius,0,'#56a49c',[3,5]);circle3(radius,height,'#56a49c',[3,5]);for(let i=0;i<8;i++){const a=i*Math.PI/4;line([radius*Math.cos(a),radius*Math.sin(a),0],[radius*Math.cos(a),radius*Math.sin(a),height],'#355e5c',1,[4,6]);}
  const tops=[];
  const [railStart,railEnd]=displayedRailInterval??[g.railMinMm,g.railMaxMm];
  for(let i=0;i<6;i++){line(railBodyPoint(g,i,railStart),railBodyPoint(g,i,railEnd),'#516878',3);tops.push(railBodyPoint(g,i,railEnd));}
  for(let i=0;i<6;i++)line(tops[i],tops[(i+1)%6],'#344c5c',2);
  if(program){const step=Math.max(1,Math.floor(program.samples.length/7000));for(let i=step;i<program.samples.length;i+=step)line(program.samples[i-step].tcp,program.samples[i].tcp,i<=index?'#7fe6ae':'#416763',i<=index?1.6:1);}
  if(!state)return;
  for(let i=0;i<state.carriages.length;i++){const color=['#60e0d1','#94b9ff','#dfabeb'][Math.floor(i/2)];line(railBodyPoint(g,i,state.heights[i]),state.carriages[i],'#a4b4c3',4);line(state.carriages[i],state.points[i],collisionDemo&&program?.samples[index]?.line===collisionDemo.line&&collisionDemo.rods.includes(i)?'#ff4545':state.valid?color:'#fa9380',3);point(state.carriages[i],'#d1dbe8',5);ctx.font='11px system-ui';for(const p of [state.carriages[i],state.points[i]]){const q=project(p);ctx.fillStyle=color;ctx.fillText(`${'ABC'[Math.floor(i/2)]}${i%2+1}`,q[0]+9,q[1]-5);}}
  const ordered=[...state.points].sort((a,b)=>Math.atan2(a[1]-state.platform[1],a[0]-state.platform[0])-Math.atan2(b[1]-state.platform[1],b[0]-state.platform[0]));polygon(ordered,'#cc8d4340','#ffa866');for(const p of state.points)point(p,'#ffa866',3);
  const R=state.rotation,tcp=state.tcp,top=state.platform,base=add(tcp,mul(matvec(R,[0,0,1]),g.toolLengthMm*.75));
  for(let i=0;i<12;i++){const a=i*Math.PI/6,b=(i+1)*Math.PI/6,p=add(base,matvec(R,[5*Math.cos(a),5*Math.sin(a),0])),q=add(base,matvec(R,[5*Math.cos(b),5*Math.sin(b),0]));polygon([tcp,p,q],'#e8a26170','#c28b4e');}line(base,top,'#ffc28b',6);point(tcp,'#ffe3bf',5);
  for(const [v,c,name]of [[[45,0,0],'#fb9e91','X'],[[0,45,0],'#9adeac','Y'],[[0,0,45],'#8fbce9','Z']]){line([0,0,0],v,c,2);const p=project(v);ctx.fillStyle=c;ctx.fillText(name,p[0]+5,p[1]);}
}
canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,yaw,pitch};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(drag){yaw=drag.yaw+(e.clientX-drag.x)*.006;pitch=Math.max(-1.2,Math.min(1.2,drag.pitch+(e.clientY-drag.y)*.006));draw();}};canvas.onpointerup=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.4,Math.min(20,zoom*Math.exp(-e.deltaY*.001)));draw();};new ResizeObserver(draw).observe(canvas);
$('wholeMachine').onclick=()=>{const range=displayedRailInterval??[g.railMinMm,g.railMaxMm],points=[[0,0,0],...g.rails.flatMap((_,i)=>range.map(h=>railBodyPoint(g,i,h))),...(state?.points??[]),...(state?.tcp?[state.tcp]:[])];const lo=[0,1,2].map(k=>Math.min(...points.map(p=>p[k]))),hi=[0,1,2].map(k=>Math.max(...points.map(p=>p[k])));cameraCenter=lo.map((v,i)=>(v+hi[i])/2);zoom=.8*Math.min(650/(Math.max(hi[0]-lo[0],hi[1]-lo[1])+80),900/(hi[2]-lo[2]+100));draw();};$('focusPart').onclick=()=>{if(program){const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(const s of program.samples)for(let i=0;i<3;i++){min[i]=Math.min(min[i],s.tcp[i]);max[i]=Math.max(max[i],s.tcp[i]);}cameraCenter=min.map((v,i)=>(v+max[i])/2);zoom=Math.min(16,400/Math.max(10,...max.map((v,i)=>v-min[i])));}else{cameraCenter=[...pose.tcp];zoom=6;}draw();};
$('home').onclick=()=>{playing=false;sweeping=false;for(const[k]of poseFields)$(k).value=k==='z'?20:0;poseFromControls();};$('orbit').onclick=()=>{sweeping=!sweeping;playing=false;if(sweeping)$('tilt').value=g.operatingTiltDeg;};
$('preset').onchange=()=>{config={...DEFAULT_GEOMETRY};if($('preset').value==='150')config.rodLengthMm=400;if($('preset').value==='relaxed'){config.rodLengthMm=600;config.jointConeDeg=80;config.railMaxMm=1000;}if($('preset').value==='long'){config.rodLengthMm=500;config.toolLengthMm=160;}for(const[k]of fields)$(k).value=config[k]??0;$('diameter').value=$('preset').value==='150'?150:200;g=geometry(config);invalidate();update();};
for(const id of ['diameter','height','spinRange','resolution'])$(id).onchange=()=>{invalidate();draw();};
function save(name,value){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type:'text/plain'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('exportProfile').onclick=()=>save('split-delta-design.json',{...profile,kinematicModel:{...profile.kinematicModel,...config},designEnvelope:{...profile.designEnvelope,diameterMm:+$('diameter').value,heightMm:+$('height').value,spinDeg:+$('spinRange').value},bounds:{min:[-+$('diameter').value/2,-+$('diameter').value/2,0],max:[+$('diameter').value/2,+$('diameter').value/2,+$('height').value]}});
function runAssessment(search=false){
  worker?.terminate();worker=new Worker('/worker.mjs',{type:'module'});$('assess').disabled=true;$('assess').textContent='Sampling workspace…';$('assessment').textContent=`Checking disk, ${g.operatingTiltDeg+g.marginDeg}° tilt cone, spin reserve, spherical-joint cones and parallel singularities${g.railTiltDeg?', including sampled build heights':''}…`;
  const fine=$('resolution').value==='fine',options={diameterMm:+$('diameter').value,heightMm:+$('height').value,spinRangeDeg:+$('spinRange').value,radialSteps:fine?6:4,azimuthSteps:fine?36:24,tiltSteps:fine?14:7};
  worker.onmessage=({data})=>{worker.terminate();worker=null;$('assess').disabled=false;$('assess').textContent='Assess cylinder with angular clearance';if(data.error){$('assessment').textContent=data.error;return;}
    report={geometry:config,...data};const a=data.reserved,o=data.operating;$('saveReport').disabled=false;if(data.search){$('diameter').value=data.search.diameterMm.toFixed(2);draw();}
    $('assessment').innerHTML=`<p class="${a.passed?'':'warning'}"><b>${a.passed?'PASS AT SAMPLED POSES':'FAIL — reduce workspace or change geometry'}</b><br>${a.samples.toLocaleString()} samples · ${a.failures.toLocaleString()} failures<br>${a.testedTiltDeg}° tilt, spin ${a.spinValues.join(' / ')}°</p><div class="metric"><small>OPERATING WORKING TRAVEL</small><strong>${a.workingTrackMm.toFixed(1)} mm</strong><small>${a.heightIndependentReach?`${a.heightMm} mm height + ${a.overheadMm.toFixed(1)} mm excursion`:`Full ${a.heightMm} mm height sampled on inclined rails`}</small></div><p>Operating travel: <b>${o.workingTrackMm.toFixed(1)} mm</b><br>Track center positions: <b>${a.railIntervalMm.map(v=>v.toFixed(1)).join(' – ')} mm</b><br>Fits configured track: <b>${a.fitsConfiguredTrack?'yes':'NO'}</b><br>Required joint cone: <b>${a.requiredJointConeDeg.toFixed(1)}°</b><br>Minimum rod / rail reserve: ${a.minRodElevationDeg.toFixed(1)}°<br>Minimum singular ratio: ${a.minSingularRatio.toFixed(4)}</p><p class="note">The angular margin applies once at operating poses. Additional probes test raw kinematic boundaries; they do not expand collision-free operation. Track extrema are sampled; use convergence checks and mechanical allowances.</p>`;
    if(data.search){const p=document.createElement('p');p.textContent=`Largest sampled diameter: ${data.search.diameterMm.toFixed(2)} mm${data.search.limitedBySearchCap?' (400 mm search cap reached)':''}. Diameter bracket ≤1 mm; angular/radial sampling uncertainty is separate.`;$('assessment').prepend(p);}
    if(a.worst){const p=document.createElement('p');p.className='warning';p.textContent=`First failure: ${a.worst.reasons.join('; ')} at TCP ${a.worst.pose.tcp.map(v=>v.toFixed(1))}, tilt ${a.worst.pose.tiltDeg.toFixed(1)}°, azimuth ${a.worst.pose.azimuthDeg}°.`;$('assessment').append(p);}
  };worker.onerror=e=>{$('assessment').textContent=e.message;$('assess').disabled=false;worker.terminate();worker=null;};worker.postMessage({geometry:config,options,search});
}
$('assess').onclick=()=>runAssessment();$('findDiameter').onclick=()=>runAssessment(true);
$('saveReport').onclick=()=>{if(report)save('split-delta-assessment.json',report);};
$('source').value='; Simulation only: TCP moves with changing head tilt\nG21\nG90\nM82\nG1 X0 Y0 Z20 A0 B0 C0 F1200 E0\nG1 X60 Y0 Z45 A0 B35 C0 F900 E0\nG1 X0 Y60 Z65 A-35 B0 C0 F900 E0\nG1 X-60 Y0 Z45 A0 B-35 C0 F900 E0\nG1 X0 Y-60 Z65 A35 B0 C0 F900 E0\nG1 X0 Y0 Z20 A0 B0 C0 F900 E0\n';
function interpret(){try{program=interpretSplitDelta(sourceText(),g,{maxSamples:500000});index=0;playing=false;$('scrub').max=program.samples.length-1;$('scrub').value=0;$('error').textContent='';$('motionStatus').textContent=`${program.commands.length} commands · ${program.samples.length} samples · ${program.seconds.toFixed(1)} s nominal (no acceleration) · simulation only${loadedSource?' · source display limited to first 50 lines':''}`;showSample();}catch(e){program=null;playing=false;$('error').textContent=e.message;$('motionStatus').textContent='Interpretation rejected; no playback.';draw();}}
function showSample(){if(!program)return;const s=program.samples[index];pose={tcp:s.tcp,rotation:eulerRotation(s.abc)};for(let i=0;i<3;i++)$('xyz'[i]).value=s.tcp[i];const n=matvec(pose.rotation,[0,0,1]),tilt=Math.acos(Math.max(-1,Math.min(1,n[2])))*180/Math.PI,az=(Math.atan2(n[1],n[0])*180/Math.PI+360)%360,base=orientation(tilt,az,0),x=matvec(pose.rotation,[1,0,0]),bx=matvec(base,[1,0,0]),by=matvec(base,[0,1,0]);$('tilt').value=tilt;$('azimuth').value=az;$('spin').value=Math.atan2(x.reduce((v,t,i)=>v+t*by[i],0),x.reduce((v,t,i)=>v+t*bx[i],0))*180/Math.PI;$('scrub').value=index;update();$('poseStatus').textContent+=` · source line ${s.line} · ${s.seconds.toFixed(2)} s`;}
$('interpret').onclick=interpret;$('source').oninput=()=>{loadedSource=null;program=null;playing=false;$('motionStatus').textContent='Source changed. Interpret again.';};$('play').onclick=()=>{if(!program)interpret();if(program){sweeping=false;if(index>=program.samples.length-1)index=0;playbackTime=program.samples[index].seconds;playing=!playing;}};$('scrub').oninput=()=>{playing=false;index=+$('scrub').value;showSample();};$('saveMotion').onclick=()=>save('split-delta-preview.sdgcode',sourceText());
$('pathFile').onchange=async()=>{const f=$('pathFile').files[0];if(!f)return;try{const text=await f.text();setSource(f.name.endsWith('.json')||f.name.endsWith('.saampath')?exportSplitDeltaPreview(JSON.parse(text)):text);interpret();}catch(e){$('error').textContent=e.message;}};
function animate(time){const dt=Math.min((time-lastTime)/1000,.1);lastTime=time;if(sweeping){$('azimuth').value=(+$('azimuth').value+dt*25)%360;poseFromControls();}if(playing&&program){playbackTime+=dt*Number($('playbackSpeed').value);while(index<program.samples.length-1&&program.samples[index+1].seconds<=playbackTime)index++;if(index===program.samples.length-1)playing=false;showSample();}requestAnimationFrame(animate);}update();requestAnimationFrame(animate);
if(new URL(location.href).searchParams.has('preview')){try{
  let sourceUrl='/preview.sdgcode',notice='Adapted wavy DENSO part: stationary bed, original part-relative TCP and commanded volume, tilt capped at 45°, minimal-twist tool frame. This changes the deposition approach and is a simulation, not a validated print.';
  const studyResponse=await fetch('/path-study.json');
  if(studyResponse.ok){
    const study=await studyResponse.json(),tilt=new URL(location.href).searchParams.get('tilt')==='40'?40:45,chosen=study.results.find(r=>r.name==='compact'&&r.config.operatingTiltDeg===tilt);
    if(chosen){
      config={...DEFAULT_GEOMETRY,...chosen.config};g=geometry(config);for(const[k]of fields)$(k).value=config[k]??0;
      displayedRailInterval=[...chosen.assessment.railIntervalMm];
      sourceUrl=`/compact-${tilt}.sdgcode`;$('diameter').value=Math.ceil(chosen.depositionBounds.centeredDiameterMm);$('height').value=Math.ceil(chosen.depositionBounds.max[2]);
      const option=document.createElement('option');option.value='study';option.textContent=chosen.label??`Wavy file · ${tilt}° · ${chosen.scale.toFixed(2)}×`;option.selected=true;$('preset').prepend(option);
      $('pathStudySection').hidden=false;
      const table=document.createElement('table');table.innerHTML='<tr><th>Head tilt</th><th>Scale</th><th>Path Ø</th></tr>';
      for(const r of study.results.filter(r=>r.name==='compact')){const row=document.createElement('tr');for(const value of [`${r.config.operatingTiltDeg}°`,`${r.scale.toFixed(2)}×`,`${r.depositionBounds.centeredDiameterMm.toFixed(1)} mm`]){const td=document.createElement('td');td.textContent=value;row.append(td);}table.append(row);}
      $('pathStudy').append(table);
      const p=document.createElement('p');p.textContent=chosen.passed===false?'Collision demonstration only. No passing print size found with these fixed dimensions. Displayed rail segments follow operating carriage extrema.':`Loaded: ${chosen.scale.toFixed(2)}× XYZ, ${tilt}° operating tilt; 4° clearance from kinematic limits. Displayed rails cover the working travel: ${chosen.assessment.workingTravelMm.toFixed(1)} mm; rail coordinates ${chosen.assessment.railIntervalMm.map(v=>v.toFixed(1)).join('–')} mm. Dimensions exclude bead thickness.`;$('pathStudy').append(p);
      for(const cap of study.results.filter(r=>r.name==='compact').map(r=>r.config.operatingTiltDeg)){const a=document.createElement('a');a.href=`/?preview=1&tilt=${cap}`;a.textContent=`View ${cap}° study →`;a.style.cssText='display:block;color:var(--cyan);margin:8px 0';$('pathStudy').append(a);}
      const warning=document.createElement('p');warning.textContent='Saved study results apply to their saved geometry. These are sampled kinematic limits; the reference cylinder is drawn to the path bounds, not a certified all-orientation workspace.';$('pathStudy').append(warning);
      notice=`Uniformly scaled wavy path including startup and travel. ${tilt===40?'The 40° study also reduces over-limit tool inclinations.':'The loaded 45° orientation sequence is retained.'} E and feed words are unchanged: this is a geometry-fit replay, not a resliced print program. Joint bodies, loads and real joint articulation remain unverified.`;
      if(study.clearance){collisionDemo=study.clearance.collisionDemo??null;notice=study.clearance.notice+' '+notice;const c=document.createElement('p');c.textContent=study.clearance.notice;$('pathStudy').append(c);}
    }
  }
  const response=await fetch(sourceUrl);if(!response.ok)throw Error('No selected preview source on this server');setSource(await response.text());$('adaptationNotice').textContent=notice;interpret();
}catch(e){$('error').textContent=e.message;}}

