import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {syncBuiltinESMExports} from 'node:module';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {InMemoryTransport} from '@modelcontextprotocol/sdk/inMemory.js';
import {createMcpAdapter} from '../../adapters/mcp/src/server.mjs';
import {createStudio,readStableBundle} from '../../studio/server.mjs';
import {createAgentRequests} from '../../studio/agent-requests.mjs';
import * as bundle from '../print/bundle.mjs';
import * as study from '../../studio/machine-study.mjs';

test('discovery, edit dispatch and geometry reads omit unrelated exports and manuals',async t=>{
  const root=await fs.mkdtemp(resolve(tmpdir(),'saam-read-scope-')),dir=resolve(root,'part');
  t.after(()=>fs.rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:100}));
  const plan=await bundle.proposedPlan('ultimaker-s5');
  plan.geometry={shape:'box',runMm:8,widthMm:8,heightMm:1};
  plan.skills['draped-skin'].enabled=false;plan.process.minimumLayerSeconds=0;
  await bundle.initBundle(dir,plan,{machineId:'ultimaker-s5'});
  await bundle.generateBundle(dir,{development:true});
  const adapter=createMcpAdapter({printsRoot:root,autoOpen:false,localExtension:{}});
  const client=new Client({name:'read-scope-test',version:'1'});
  const [a,b]=InMemoryTransport.createLinkedPair();await adapter.server.connect(b);await client.connect(a);
  t.after(async()=>{await client.close();await adapter.close();});
  const call=async(name,args={})=>{const result=await client.callTool({name,arguments:args});assert.ok(!result.isError,JSON.stringify(result));return JSON.parse(result.content[0].text);};
  // Finish initialization notifications before recording individual operations.
  await call('get_studio_requests');
  const readFile=fs.readFile,readdir=fs.readdir,clone=globalThis.structuredClone;
  let reads=[],scans=0,motionCopies=0;
  fs.readFile=async function(path,...args){reads.push(String(path instanceof URL?fileURLToPath(path):path).replaceAll('\\','/'));return readFile.call(this,path,...args);};
  fs.readdir=async function(...args){scans++;return readdir.apply(this,args);};
  globalThis.structuredClone=(value,...args)=>{if(value?.moves?.length)motionCopies++;return clone(value,...args);};
  syncBuiltinESMExports();
  t.after(()=>{fs.readFile=readFile;fs.readdir=readdir;globalThis.structuredClone=clone;syncBuiltinESMExports();});
  const reset=()=>{reads=[];scans=0;motionCopies=0;};
  await call('read_skill',{skillId:'text'});
  assert.deepEqual(reads.filter(path=>path.endsWith('/SKILL.md')).map(path=>path.split('/').at(-2)),['text']);
  reset();const listing=await call('list_prints');
  assert.equal(listing[0].programChecked,false);
  assert.equal(reads.some(path=>/\/(geometry|exports)\//.test(path)),false,'discovery needs neither native geometry nor export contents');
  reset();const saved=await call('get_print',{printId:'part'});
  assert.equal(saved.programChecked,true);assert.ok(saved.exportHash);assert.equal(motionCopies,0,'a checked summary does not clone motion arrays');
  reset();const edited=await call('adjust_print',{printId:'part',expectedRevision:saved.revision,patch:{}});
  assert.equal(edited.programChecked,false);assert.equal(edited.generation.current,null);
  assert.equal(reads.some(path=>path.includes('/exports/')),false,'editing must not inspect the old export');
  reset();await readStableBundle(bundle,dir,{program:false});
  assert.equal(reads.some(path=>path.includes('/exports/')),false,'geometry fingerprints must not discover old export bytes');
  const requests=createAgentRequests(root),request=await requests.begin({directory:dir,instruction:'Read one request'});
  reset();assert.equal((await requests.get(request.id)).id,request.id);assert.equal(scans,0,'ID lookup does not enumerate history');
  const damaged='f'.repeat(32);await fs.writeFile(resolve(root,'.studio-requests',damaged+'.json'),'{damaged');
  const records=await requests.list();assert.equal(records.find(r=>r.id===damaged).kind,'diagnostic');
  assert.ok(records.some(r=>r.id===request.id),'one malformed record cannot hide valid work');
  await requests.update(request.id,{status:'cancelled'});
  // Source integrity remains a review boundary even after a warm metadata read.
  await fs.appendFile(resolve(dir,'exports/griffin-gcode/part.gcode'),'\n; altered');
  const checked=await call('get_print',{printId:'part'});assert.match(checked.programError,/files changed/);
  const studio=createStudio(dir,{libraryRoot:root,localExtension:{}});
  await new Promise(done=>studio.listen(0,'127.0.0.1',done));t.after(()=>studio.shutdown());
  const url='http://127.0.0.1:'+studio.address().port;
  const state=await(await fetch(url+'/api/state')).json(),revision=await(await fetch(url+'/api/revision')).json();
  assert.equal(state.fingerprint,revision.fingerprint,'state and revision use the same read scope');
});

test('machine-study geometry omits motion and warm revision polls detect source edits without rereading unchanged bytes',async t=>{
  const root=await fs.mkdtemp(resolve(tmpdir(),'saam-study-read-'));
  t.after(()=>fs.rm(root,{recursive:true,force:true}));
  await fs.writeFile(resolve(root,'plan.json'),JSON.stringify({schema:'saam-machine-study/1',output:'machine-study',studyBounds:{min:[0,0,0],max:[1,1,1]}}));
  await fs.writeFile(resolve(root,'machine.json'),JSON.stringify({name:'Read-scope fixture'}));
  await fs.writeFile(resolve(root,'motion.json'),'deliberately not a valid program');
  assert.equal((await study.loadBundle(root,{program:false})).program,undefined);
  const before=await study.bundleFingerprint(root),readFile=fs.readFile;let motionReads=0;
  fs.readFile=async function(path,...args){if(String(path).endsWith('motion.json'))motionReads++;return readFile.call(this,path,...args);};syncBuiltinESMExports();
  t.after(()=>{fs.readFile=readFile;syncBuiltinESMExports();});
  assert.equal(await study.bundleFingerprint(root),before);assert.equal(motionReads,0);
  await fs.appendFile(resolve(root,'motion.json'),' changed');
  assert.notEqual(await study.bundleFingerprint(root),before);assert.equal(motionReads,1);
  await assert.rejects(study.loadBundle(root),/JSON/);
});
