import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {once} from 'node:events';
import {createTour,tourExample,referenceAdapter} from '../../studio/tour.mjs';
import {surfaceDrapePlan} from '../../examples/prints/surface-drape/recipe.mjs';
import {adjustBundle,loadBundle,generateBundle} from '../print/bundle.mjs';
import {createStudio} from '../../studio/server.mjs';
import {createAgentRequests} from '../../studio/agent-requests.mjs';
async function library(t){const dir=await mkdtemp(join(tmpdir(),'saam-tour-'));t.after(()=>rm(dir,{recursive:true,force:true,maxRetries:5,retryDelay:100}));return dir;}
async function ready(tour,dir){const state=await loadBundle(dir,{program:'source'});return tour.acknowledgeView(dir,{revision:state.revision,exportHash:state.exportHash},state);}
async function editFin(copy){const {plan}=await loadBundle(copy,{program:false});plan.geometry.parts[1].geometry.heightMm+=1;await adjustBundle(copy,{geometry:plan.geometry});}

test('tour gates require geometry edits, file selection, five seconds of playback and settings edits',async t=>{
  let time=1000;const dir=await library(t),tour=createTour(dir,{now:()=>time}),{directory:starter}=await tour.action('resume');
  assert.equal((await tour.info()).canNext,false);
  await assert.rejects(tour.action('step',1),/Complete/);
  await adjustBundle(starter,{process:{planarSpeedMmS:30}});assert.equal((await tour.info()).canNext,false,'settings do not satisfy the geometry task');
  const editing=createAgentRequests(dir),editRequest=await editing.begin({directory:starter,instruction:'Change the fin'});
  await editFin(starter);assert.equal((await tour.info()).canNext,false);await ready(tour,starter);assert.equal((await tour.info()).canNext,true,'visible geometry unlocks without waiting for the chat acknowledgement');
  await editing.update(editRequest.id);
  const {directory:roof}=await tour.action('step',1);assert.notEqual(roof,starter);
  assert.equal((await tour.info()).canNext,true);
  const state=await loadBundle(roof,{program:false}),heightsMm=state.plan.geometry.heightsMm.map(row=>row.map(z=>z+.1));
  await adjustBundle(roof,{geometry:{heightsMm}});
  await tour.action('step',2);assert.equal((await tour.info()).canNext,false);
  await assert.rejects(tour.action('step',3),/Complete/);
  await assert.rejects(tour.select(starter),/startAt/);
  await tour.setStartAt({layer:12});await tour.select(starter);assert.equal((await tour.info()).step,3);await tour.action('step',4);
  await tour.playback('tick');time+=6000;await tour.playback('tick');assert.equal((await tour.info()).canNext,false,'ticks without Play do not count');
  await tour.playback('play');for(let i=0;i<4;i++){time+=500;await tour.playback('tick');}
  await tour.playback('pause');time+=10000;await tour.playback('pause');assert.equal((await tour.info()).watchedMs,2000,'paused time is not viewing');
  await tour.playback('play');for(let i=0;i<6;i++){time+=500;await tour.playback('tick');}
  assert.equal((await tour.info()).canNext,true);
  await tour.action('step',5);assert.match((await tour.info()).agentInstruction,/rectilinear.*grid.*triangles.*gyroid.*concentric/);
  await editFin(starter);assert.equal((await tour.info()).canNext,false,'a geometry change alone does not count as a settings change');
  await adjustBundle(starter,{skills:{'planar-infill':{pattern:'grid'}}});assert.equal((await tour.info()).canNext,false);
  await generateBundle(starter,{development:true});assert.equal((await tour.info()).canNext,false,'generation alone is not a visible preview');
  const fresh=await loadBundle(starter,{program:'source'});await tour.acknowledgeView(starter,{revision:'stale',exportHash:fresh.exportHash},fresh);assert.equal((await tour.info()).canNext,false);
  for(const request of await createAgentRequests(dir).list())await createAgentRequests(dir).update(request.id,{status:'completed'});
  await ready(tour,starter);assert.equal((await tour.info()).canNext,true);
  const requests=createAgentRequests(dir),request=await requests.begin({directory:starter,instruction:'One more settings change'});
  assert.equal((await tour.info()).canNext,false,'outstanding work relocks Next');
  await requests.update(request.id,{status:'completed'});assert.equal((await tour.info()).canNext,true);
  await tour.action('step',6);await tour.action('step',7);
  await assert.rejects(tour.action('finish'),/Download the print file/);
  await tour.downloaded(fresh.exportHash);
  await tour.action('finish');assert.match((await tour.info()).agentInstruction,/ordinary chat text congratulating/);
  assert.deepEqual((await loadBundle(roof,{program:false})).plan.geometry.heightsMm,heightsMm,'switching preserves roof edits');
});
test('resuming and restarting preserve copies; exit is available at a locked step',async t=>{
  const dir=await library(t),tour=createTour(dir),{directory:first}=await tour.action('resume');
  const starterSource=await readFile(join(first,'plan.json'),'utf8');
  await editFin(first);await ready(tour,first);
  const {directory:roof}=await tour.action('step',1);
  const roofSource=await readFile(join(roof,'plan.json'),'utf8');
  await adjustBundle(roof,{process:{planarSpeedMmS:30}});
  const editedRoof=await readFile(join(roof,'plan.json'),'utf8');
  await tour.setStartAt({layer:12});
  await tour.action('exit');assert.equal((await tour.info()).active,false);
  assert.equal((await tour.action('resume')).directory,roof);
  assert.equal((await tour.info()).step,1,'explicit resume keeps the saved lesson');
  assert.equal((await tour.info()).canNext,true);
  const {directory:second}=await tour.action('fresh');assert.notEqual(second,first);
  assert.equal((await tour.info()).step,0,'new tours always begin with the first lesson');
  assert.equal((await tour.info()).startAt,null,'a previous model’s playback layer is not inherited');
  const progress=await tour.info(),newRoof=join(dir,'tour',progress.copies['surface-drape']);
  assert.notEqual(newRoof,roof);
  assert.equal(await readFile(join(second,'plan.json'),'utf8'),starterSource,'new starter uses the bundled recipe');
  assert.equal(await readFile(join(newRoof,'plan.json'),'utf8'),roofSource,'new roof uses the bundled recipe');
  assert.equal(await readFile(join(roof,'plan.json'),'utf8'),editedRoof,'earlier roof edits stay saved');
  const roofState=await referenceAdapter({loadBundle}).loadBundle(newRoof,{program:false});
  assert.deepEqual(roofState.plan.geometry,surfaceDrapePlan().geometry,'the current roof shape is preserved');
  assert.equal(roofState.review.generation,null,'tour startup does not generate or inherit a toolpath');
  assert.equal(roofState.geometryApproved,false);
  assert.equal((await tour.info()).canNext,false);assert.ok(await readFile(join(first,'plan.json')));
  assert.equal(await createTour(dir).landing(),second);
});
test('editing a recipe-created roof keeps the tour identity and edited copy',async t=>{
  const dir=await library(t),tour=createTour(dir),{directory:starter}=await tour.action('resume');await editFin(starter);await ready(tour,starter);
  const {directory:roof}=await tour.action('step',1);
  await adjustBundle(roof,{process:{planarSpeedMmS:30}});
  const state=await referenceAdapter({loadBundle}).loadBundle(roof,{program:false});
  assert.equal(state.tourExample.id,'surface-drape');
  assert.equal(state.plan.process.planarSpeedMmS,30);
  assert.equal(await createTour(dir).landing(),roof);
});
test('Studio file selection confirms geometry; completing the STL lesson first loads toolpath',async t=>{
  const dir=await library(t),tour=createTour(dir),{directory:starter}=await tour.action('resume');await editFin(starter);await ready(tour,starter);
  await tour.action('step',1);await tour.action('step',2);await tour.setStartAt({layer:12});
  const server=createStudio(starter,{libraryRoot:dir});t.after(()=>server.shutdown());server.listen(0,'127.0.0.1');await once(server,'listening');
  const url='http://127.0.0.1:'+server.address().port,html=await(await fetch(url)).text(),token=html.match(/name="saam-token" content="([^"]+)"/)[1];
  const post=(route,data,auth=token)=>fetch(url+'/api/'+route,{method:'POST',headers:{Origin:url,'X-SAAM-Token':auth,'Content-Type':'application/json'},body:JSON.stringify(data)});
  assert.equal((await post('open',{path:starter},'bad')).status,403);
  assert.equal((await(await fetch(url+'/api/prints')).json()).prints.length,2);
  const opened=await post('open',{path:starter});assert.equal(opened.status,200,await opened.text());
  let state=await(await fetch(url+'/api/state')).json();assert.equal(state.program,undefined);assert.equal(state.review.generation,null);
  assert.equal(state.geometryApproved,true);assert.equal(state.planApproved,false);assert.equal(state.toolpathApproved,false);
  assert.equal(state.tour.step,3,'selection advances straight to the optional import lesson');
  const preparation=await(await fetch(url+'/api/preparation')).json();
  assert.equal(preparation.planHash,state.planHash);assert.ok(['preparing','ready'].includes(preparation.status));
  assert.ok(preparation.progress.stage,'step 4 starts preparation while geometry remains visible');
  assert.equal((await post('tour',{action:'step',step:4})).status,200);
  state=await(await fetch(url+'/api/state')).json();assert.ok(state.program);assert.equal(state.review.generation.mode,'production');
  assert.equal(state.toolpathApproved,false,'preparation does not confirm the final settings');
  assert.equal((await post('generate',{planHash:'stale',development:false})).status,400);
  assert.equal((await post('tour',{action:'step',step:5})).status,400);
  assert.equal((await post('approve',{stage:'geometry',actor:'SYNTHETIC tour test',revision:state.revision})).status,400);
  assert.equal((await post('tour',{action:'exit'})).status,200);
  assert.equal(await tourExample(starter),null);
  state=await(await fetch(url+'/api/state')).json();assert.equal(state.tour.active,false);
  assert.equal((await post('approve',{stage:'geometry',actor:'SYNTHETIC tour test',revision:state.revision})).status,200);
});
