// Reference post-processor: translates an approved process plan
// (schemas/process-plan/process-plan.schema.json) into DobotStudio Pro
// Lua for the reference-dobot-mg400-struderbot machine. No dependencies.
//
// Translates or rejects. Never redesigns geometry — see
// ../../../docs/architecture/operations-vs-postprocessors.md. Where the
// input doesn't give this post-processor enough to make a safe choice on
// its own (an untraveled gap between two printed paths, for example) it
// reports a warning rather than silently inventing a fix.

const EPSILON_MM = 0.01;

function distance(a, b) {
  return Math.hypot(a.x - b.x, a.y - b.y, a.z - b.z);
}

function luaNumber(value) {
  return Number.isFinite(value) ? String(Number(value.toFixed(4))) : "0";
}

// Refuses to translate anything that isn't explicitly, currently approved
// for export. This is the one place in SAAM's reference toolchain where
// that gate is actually enforced in code, not just documented.
function assertExportable(plan) {
  if (!plan || typeof plan !== "object") {
    throw new Error("Refusing to translate: no process plan was given.");
  }
  if (plan.machine?.id !== "reference-dobot-mg400-struderbot") {
    throw new Error(
      `Refusing to translate: this post-processor only accepts plans resolved against "reference-dobot-mg400-struderbot" (got "${plan.machine?.id}").`
    );
  }
  if (!plan.approval) {
    throw new Error("Refusing to translate: process plan has no approval record.");
  }
  if (plan.approval.revision !== plan.revision) {
    throw new Error(
      `Refusing to translate: approval is for revision ${plan.approval.revision}, but the plan is at revision ${plan.revision}. Any change invalidates its approval.`
    );
  }
  if (plan.approval.scope !== "executable-export" && plan.approval.scope !== "machine-control") {
    throw new Error(
      `Refusing to translate: approval scope "${plan.approval.scope}" does not authorize executable export.`
    );
  }
}

function flattenPrintPoints(plan) {
  const points = [];
  const warnings = [];
  let previous = null;

  for (const operation of plan.operations) {
    for (const pathEntry of operation.paths) {
      if (pathEntry.intent !== "print") continue;
      if (!pathEntry.points.length) continue;

      const first = pathEntry.points[0];
      if (previous && distance(previous, first) > EPSILON_MM) {
        warnings.push({
          code: "disjoint-transition",
          message:
            `A ${distance(previous, first).toFixed(2)} mm gap separates "${points.at(-1)?.family}" ` +
            `(layer ${points.at(-1)?.layer}) from "${pathEntry.family}" (layer ${pathEntry.layer}). ` +
            "This post-processor travels it linearly with extrusion left on, per the project's " +
            "one-continuous-extrusion-window convention, rather than cycling PenOff/PenOn — but a gap " +
            "this size was not designed as a deliberate printed transition by the operation that produced it.",
          from: previous,
          to: first,
        });
      }

      pathEntry.points.forEach((point) => {
        points.push({ ...point, family: pathEntry.family, layer: pathEntry.layer });
      });
      previous = pathEntry.points.at(-1);
    }
  }

  return { points, warnings };
}

function boundingRadius(points) {
  return points.reduce((max, p) => Math.max(max, Math.hypot(p.x, p.y)), 0);
}

function renderGlobalLua(instanceProfile) {
  const cal = instanceProfile?.xyCalibration ?? { enabled: false, scaleX: 1, scaleYAtX0: 1 };
  const bedZ = instanceProfile?.bedZ ?? 0;
  const tool = instanceProfile?.frames?.activeTool ?? 1;
  const user = instanceProfile?.frames?.activeUser ?? 1;
  const penDo = instanceProfile?.io?.extrusionRelayOutput ?? "PEN_DO";

  return `--=========================================================
-- global.lua (generated by dobot-lua-postprocessor)
-- Shared configuration and helpers for the reference StruderBot install.
-- Instance calibration below comes from the supplied instance profile.
-- Replace it with your own unit's measured values before trusting output.
--=========================================================

ACTIVE_TOOL = ${luaNumber(tool)}
ACTIVE_USER = ${luaNumber(user)}

BED_Z = ${luaNumber(bedZ)}
JUMP_SPEED = 100
JUMP_ACCEL = 100
PRINT_SPEED = 2
PRINT_ACCEL = 20
THICK_PRINT_SPEED = 1.0 -- tested speed floor; do not go lower without a deliberate tuning test
PEN_ON_DWELL_MS = 4000
PEN_OFF_DWELL_MS = 500

XY_CALIBRATION_ENABLED = ${cal.enabled ? "true" : "false"}
CAL_X_SCALE = ${luaNumber(cal.scaleX ?? 1)}
CAL_Y_SCALE_AT_X0 = ${luaNumber(cal.scaleYAtX0 ?? 1)}

PEN_IS_ON = false

function CalibratedXY(x, y)
    if not XY_CALIBRATION_ENABLED then
        return x, y
    end
    return x * CAL_X_SCALE, y * CAL_Y_SCALE_AT_X0
end

function P(x, y, z, r)
    local px, py = CalibratedXY(x, y)
    return { coordinate = {px, py, z, r}, tool = ACTIVE_TOOL, user = ACTIVE_USER }
end

-- Fast in-plane travel. Extrusion may still be on; kept linear on purpose.
function J(x, y, z, r)
    MovL(P(x, y, z, r), { SpeedL = JUMP_SPEED, AccL = JUMP_ACCEL })
end

-- Printed linear move.
function L(x, y, z, r)
    MovL(P(x, y, z, r), { SpeedL = THICK_PRINT_SPEED, AccL = PRINT_ACCEL })
end

function PenOn()
    if not PEN_IS_ON then
        DO(${JSON.stringify(String(penDo))}, 1)
        PEN_IS_ON = true
        Wait(PEN_ON_DWELL_MS)
    end
end

function PenOff()
    if PEN_IS_ON then
        DO(${JSON.stringify(String(penDo))}, 0)
        PEN_IS_ON = false
        Wait(PEN_OFF_DWELL_MS)
    else
        DO(${JSON.stringify(String(penDo))}, 0)
    end
end
`;
}

function renderSrc0Lua() {
  return `--=========================================================
-- src0.lua (generated by dobot-lua-postprocessor)
-- Entry point. Wire to Remote I/O per your own instance configuration;
-- see machines/reference-dobot-mg400-struderbot/README.md.
--=========================================================

PenOff()
`;
}

function renderSrc1Lua(points, leadIn) {
  const lines = [];
  lines.push("--=========================================================");
  lines.push("-- src1.lua (generated by dobot-lua-postprocessor)");
  lines.push("-- One continuous extrusion window: one PenOn, one final PenOff.");
  lines.push("--=========================================================");
  lines.push("");
  lines.push("function RunPlan()");
  lines.push(`    local r0 = 180`);
  lines.push("");
  lines.push(
    `    MovJ(P(${luaNumber(leadIn.x)}, ${luaNumber(leadIn.y)}, ${luaNumber(leadIn.z)}, r0), { SpeedJ = JUMP_SPEED, AccJ = JUMP_ACCEL })`
  );
  lines.push(`    J(${luaNumber(leadIn.x)}, ${luaNumber(leadIn.y)}, ${luaNumber(points[0].z)}, r0)`);
  lines.push("    PenOn()");

  let previous = null;
  for (const point of points) {
    const fn = previous && distance(previous, point) > EPSILON_MM ? "J" : "L";
    lines.push(`    ${fn}(${luaNumber(point.x)}, ${luaNumber(point.y)}, ${luaNumber(point.z)}, r0)`);
    previous = point;
  }

  lines.push("");
  lines.push("    PenOff()");
  lines.push(`    J(${luaNumber(leadIn.x)}, ${luaNumber(leadIn.y)}, ${luaNumber(leadIn.z)}, r0)`);
  lines.push("end");
  lines.push("");
  return lines.join("\n");
}

/**
 * @param {object} args
 * @param {object} args.plan - an approved process plan (schemas/process-plan/)
 * @param {object} [args.instanceProfile] - this unit's calibration; see instance-profile.example.json
 * @returns {{ files: Record<string,string>, warnings: Array }}
 */
export function translate({ plan, instanceProfile } = {}) {
  assertExportable(plan);

  const { points, warnings } = flattenPrintPoints(plan);
  if (!points.length) {
    throw new Error("Refusing to translate: the plan has no print-intent points to emit.");
  }

  const radius = boundingRadius(points);
  const leadInMargin = 20;
  const leadIn = {
    x: radius + leadInMargin,
    y: 0,
    z: Math.max(...points.map((p) => p.z)) + 20,
  };

  return {
    files: {
      "global.lua": renderGlobalLua(instanceProfile),
      "src0.lua": renderSrc0Lua(),
      "src1.lua": renderSrc1Lua(points, leadIn),
    },
    warnings,
  };
}
