// Reference post-processor: translates an approved process plan
// (schemas/process-plan/process-plan.schema.json) into DobotStudio Pro
// Lua for the reference-dobot-mg400-struderbot machine. No dependencies.
//
// Translates or rejects. Never redesigns geometry — see
// ../../../docs/architecture/operations-vs-postprocessors.md. Where the
// input doesn't give this post-processor enough to make a safe choice on
// its own (an untraveled gap between two printed paths, for example) it
// reports a warning rather than silently inventing a fix.

const EPSILON_MM = 0.01;

function distance(a, b) {
  return Math.hypot(a.x - b.x, a.y - b.y, a.z - b.z);
}

function luaNumber(value) {
  return Number.isFinite(value) ? String(Number(value.toFixed(4))) : "0";
}

// Refuses to translate anything that isn't explicitly, currently approved
// for export. This is the one place in SAAM's reference toolchain where
// that gate is actually enforced in code, not just documented.
function assertExportable(plan, machineId) {
  if (!plan || typeof plan !== "object") {
    throw new Error("Refusing to translate: no process plan was given.");
  }
  if (plan.machine?.id !== machineId) {
    throw new Error(
      `Refusing to translate: this post-processor only accepts plans resolved against "${machineId}" (got "${plan.machine?.id}").`
    );
  }
  if (!plan.approval) {
    throw new Error("Refusing to translate: process plan has no approval record.");
  }
  if (plan.approval.revision !== plan.revision) {
    throw new Error(
      `Refusing to translate: approval is for revision ${plan.approval.revision}, but the plan is at revision ${plan.revision}. Any change invalidates its approval.`
    );
  }
  if (plan.approval.scope !== "executable-export" && plan.approval.scope !== "machine-control") {
    throw new Error(
      `Refusing to translate: approval scope "${plan.approval.scope}" does not authorize executable export.`
    );
  }
}

function collectMoves(plan) {
  const moves = [], warnings = [];
  let previous = null;
  for (const operation of plan.operations) {
    for (const path of operation.paths) {
      if (!path.points.length) continue;
      if (!['print', 'travel'].includes(path.intent)) throw new Error('Unknown path intent.');
      const first = path.points[0];
      if (previous && distance(previous, first) > EPSILON_MM) {
        const gapMm = distance(previous, first);
        warnings.push({ code: 'disjoint-transition', gapMm: Number(gapMm.toFixed(2)),
          message: `A ${gapMm.toFixed(2)} mm gap precedes "${path.family}" (layer ${path.layer}). It is a linear travel with no planned hop. Set travelHopHeight when generating operations to include reviewed transition coordinates.`,
          from: previous, to: first });
        moves.push({ ...first, intent: 'travel' });
      } else if (!previous) moves.push({ ...first, intent: 'travel' });
      // The first point locates a path; only subsequent points command its strokes.
      for (const p of path.points.slice(1)) moves.push({ ...p, intent: path.intent });
      previous = path.points.at(-1);
    }
  }
  return { moves, warnings };
}

function boundingRadius(points) {
  return points.reduce((max, p) => Math.max(max, Math.hypot(p.x, p.y)), 0);
}

function renderGlobalLua(instanceProfile, stopOnTravel = false) {
  const cal = instanceProfile?.xyCalibration ?? { enabled: false, scaleX: 1, scaleYAtX0: 1 };
  const bedZ = instanceProfile?.bedZ ?? 0;
  const tool = instanceProfile?.frames?.activeTool ?? 1;
  const user = instanceProfile?.frames?.activeUser ?? 1;
  const penDo = instanceProfile?.io?.extrusionRelayOutput ?? "PEN_DO";

  return `--=========================================================
-- global.lua (generated by dobot-lua-postprocessor)
-- Shared configuration and helpers for the reference StruderBot install.
-- Instance calibration below comes from the supplied instance profile.
-- Replace it with your own unit's measured values before trusting output.
--=========================================================

ACTIVE_TOOL = ${luaNumber(tool)}
ACTIVE_USER = ${luaNumber(user)}

BED_Z = ${luaNumber(bedZ)}
JUMP_SPEED = 100
JUMP_ACCEL = 100
PRINT_SPEED = 2
PRINT_ACCEL = 20
THICK_PRINT_SPEED = 1.0 -- tested speed floor; do not go lower without a deliberate tuning test
PEN_ON_DWELL_MS = ${stopOnTravel ? luaNumber(instanceProfile?.extrusionTiming?.onDwellMs ?? 0) : 4000}
PEN_OFF_DWELL_MS = ${stopOnTravel ? luaNumber(instanceProfile?.extrusionTiming?.offDwellMs ?? 0) : 500}

XY_CALIBRATION_ENABLED = ${cal.enabled ? "true" : "false"}
CAL_X_SCALE = ${luaNumber(cal.scaleX ?? 1)}
CAL_Y_SCALE_AT_X0 = ${luaNumber(cal.scaleYAtX0 ?? 1)}

PEN_IS_ON = false

function CalibratedXY(x, y)
    if not XY_CALIBRATION_ENABLED then
        return x, y
    end
    return x * CAL_X_SCALE, y * CAL_Y_SCALE_AT_X0
end

function P(x, y, z, r)
    local px, py = CalibratedXY(x, y)
    return { coordinate = {px, py, z, r}, tool = ACTIVE_TOOL, user = ACTIVE_USER }
end

-- Fast in-plane travel. Extrusion may still be on; kept linear on purpose.
function J(x, y, z, r)
    MovL(P(x, y, z, r), { SpeedL = JUMP_SPEED, AccL = JUMP_ACCEL })
end

-- Printed linear move.
function L(x, y, z, r)
    MovL(P(x, y, z, r), { SpeedL = THICK_PRINT_SPEED, AccL = PRINT_ACCEL })
end

function PenOn()
    if not PEN_IS_ON then
        DO(${JSON.stringify(String(penDo))}, 1)
        PEN_IS_ON = true
        Wait(PEN_ON_DWELL_MS)
    end
end

function PenOff()
    if PEN_IS_ON then
        DO(${JSON.stringify(String(penDo))}, 0)
        PEN_IS_ON = false
        Wait(PEN_OFF_DWELL_MS)
    else
        DO(${JSON.stringify(String(penDo))}, 0)
    end
end
`;
}

function renderSrc0Lua() {
  return `--=========================================================
-- src0.lua (generated by dobot-lua-postprocessor)
-- Entry point. Wire to Remote I/O per your own instance configuration;
-- see machines/reference-dobot-mg400-struderbot/README.md.
--=========================================================

PenOff()
`;
}

function renderSrc1Lua(moves, leadIn, stopOnTravel) {
  const lines = [stopOnTravel ? '-- SAAM machine=dobot-stop' : '-- SAAM machine=reference-dobot-mg400-struderbot', '-- Generated Dobot plan. Travel intent is independent of relay state.',
    stopOnTravel ? '-- Extrusion off during travel.' : '-- One continuous extrusion window.', '', 'function RunPlan()', '    local r0 = 180'];
  const emit = (fn, p, intent) => lines.push(`    ${fn}(${luaNumber(p.x)}, ${luaNumber(p.y)}, ${luaNumber(p.z)}, r0) -- SAAM intent=${intent}`);
  lines.push(`    MovJ(P(${luaNumber(leadIn.x)}, ${luaNumber(leadIn.y)}, ${luaNumber(leadIn.z)}, r0), { SpeedJ = JUMP_SPEED, AccJ = JUMP_ACCEL }) -- SAAM intent=travel`);
  let penOn = false;
  for (const move of moves) {
    if (move.intent === 'print' && !penOn) { lines.push('    PenOn()'); penOn = true; }
    if (move.intent === 'travel' && stopOnTravel && penOn) { lines.push('    PenOff()'); penOn = false; }
    emit(move.intent === 'travel' ? 'J' : 'L', move, move.intent);
  }
  if (penOn) lines.push('    PenOff()');
  emit('J', leadIn, 'travel');
  lines.push('end', '');
  return lines.join('\n');
}

/**
 * @param {object} args
 * @param {object} args.plan - an approved process plan (schemas/process-plan/)
 * @param {object} [args.instanceProfile] - this unit's calibration; see instance-profile.example.json
 * @returns {{ files: Record<string,string>, warnings: Array }}
 */
export function translateDobot({ plan, instanceProfile } = {}, stopOnTravel = false) {
  assertExportable(plan, stopOnTravel ? "dobot-stop" : "reference-dobot-mg400-struderbot");
  if (stopOnTravel) {
    for (const key of ["onDwellMs", "offDwellMs"]) {
      const value = instanceProfile?.extrusionTiming?.[key] ?? 0;
      if (!Number.isFinite(value) || value < 0) throw new Error(`extrusionTiming.${key} must be a finite non-negative number.`);
    }
  }

  const { moves: points, warnings } = collectMoves(plan);
  if (!points.some((p) => p.intent === "print")) {
    throw new Error("Refusing to translate: the plan has no print-intent points to emit.");
  }

  const radius = boundingRadius(points);
  const leadInMargin = 20;
  const leadIn = {
    x: radius + leadInMargin,
    y: 0,
    z: points.reduce((top, p) => Math.max(top, p.z), -Infinity) + 20,
  };

  return {
    files: {
      "global.lua": renderGlobalLua(instanceProfile, stopOnTravel),
      "src0.lua": renderSrc0Lua(),
      "src1.lua": renderSrc1Lua(points, leadIn, stopOnTravel),
    },
    warnings,
  };
}

export function translate(args) { return translateDobot(args, false); }
